### ISSUE TITLE
Force `nowrap` in new window

### ISSUE THREAD

**Issue by tjdevries** [rcarriga/nvim-notify#1]
Should probably do something like:

`vim.wo[win].wrap = false` after you create the window (or nvim_win_set_option, however you prefer). Otherwise you get pretty goofy wrapping problems as the window expands.

**Comment by rcarriga** [comment]
Hmm TIL about `vim.wo` :sweat_smile: Thanks for the suggestion!

**Comment by tjdevries** [comment]
Thanks :) very cool plugin!
