### ISSUE TITLE
Interference with custom hightlights

### ISSUE THREAD

**Issue by lukoshkin** [rcarriga/nvim-notify#100]
Having both [project.nvim](https://github.com/ahmedkhalf/project.nvim) and this wonderful plugin erases the custom highlighting I made for trailing whitespaces. Commenting out just one of the two solves the problem (at least in some contexts -- I didn't test for all possible situations). I will try to prepare MWE if you are not aware of this problem already.

**Comment by rcarriga** [comment]
I'm not at all sure what you mean by this. You'll have to provide more information

**Comment by lukoshkin** [comment]
Here is a minimal working example demonstrating the problem. Almost minimal.
To reproduce it, you also need a **folder** having 1) `.git` and 2) any file containing trailing whitespaces (I put it in the second code section below)

So, when you enter the buffer, according to settings, you have trailing whitespaces highlighted in red (or brown if the buffer type is markdown). You also receive a notification (right after you entered the buffer) that your CWD is changed to the root of the repository. (Note: for that to happen **you must open it outside of the repo in which the file is located**). With the notification disappearing, the highlighting also disappears. I guess it is not supposed to clear user highlights.

init.lua
```lua
local packer = require 'packer'

packer.init {
  display = {
    open_fn = function ()
      return require('packer.util').float {
        border = 'rounded'
      }
    end,
  },
}

packer.startup(function (use)
  use 'wbthomason/packer.nvim'

  use {
    'rcarriga/nvim-notify',
    config = function ()
      vim.notify = require'notify'
    end
  }

  use {
    'ahmedkhalf/project.nvim',
    config = function()
      require("project_nvim").setup {
        -- manual_mode = true,
        silent_chdir = false,
      }
    end
  }
end)

vim.opt.termguicolors = true

vim.cmd [[
  highlight! Normal guibg=Black guifg=White
  highlight! ExtraWhitespace ctermbg=211 guibg=palevioletred
  au! FileType markdown hi ExtraWhitespace ctermbg=brown guibg=rosybrown

  "" Pattern matching for au is different:
  "" to exclude buffer names with leading underscores, we put
  "" 'negative lookbehind' after the star expression.
  au! BufWinEnter *\(_\)\@<! if len(bufname()) > 0
    \| match ExtraWhitespace /\s\+$/
    \| endif

  au! InsertEnter * if len(bufname()) > 0
    \| match ExtraWhitespace /\s\+\%#\@<!$/
    \| endif

  au! InsertLeave * if len(bufname()) > 0
    \| match ExtraWhitespace /\s\+$/
    \| endif

  au! BufWinLeave *\(_\)\@<! call clearmatches()
]]
```

file_with_trailing_whitespaces.py
```
##  
  
##
  
```

https://user-images.githubusercontent.com/44115822/172024694-a1c2ae99-7a59-4055-b08f-243d51314ed7.mp4

**Comment by rcarriga** [comment]
Your `BufWinLeave` autocmd assumes that the buffer being removed is the current one but that's not the case here. When a notification buffer is hidden, the matches are being cleared for the current window. You need to pass the window to clear matches for
```vim
  au! BufWinLeave *\(_\)\@<! call clearmatches(bufwinid(expand("<abuf>")))
```

**Comment by lukoshkin** [comment]
Oh yes, thanks!
I was looking for sth like "clearmatches" in your code but never gave a thought to it that the problem was on my end. Sorry for disturbing you!
