### ISSUE TITLE
Highlight group 'Normal' has no background highlight.  Please provide an RGB hex value or highlight group with a background value for 'background_colour' option  Defaulting to #000000

### ISSUE THREAD

**Issue by Yan-weihao** [rcarriga/nvim-notify#101]
I try to use transparent window but it gives warning
<img width="960" alt="image" src="https://user-images.githubusercontent.com/61379647/172001288-1719ba83-9794-4b7c-8545-a9ba4cfaf8b8.png">

**Comment by rcarriga** [comment]
I've improved the warning message, let me know if it is still unclear :smile:

**Comment by Yan-weihao** [comment]
> 
this is the new error
<img width="960" alt="2022-06-05_21-28" src="https://user-images.githubusercontent.com/61379647/172053010-a4bb0a1d-cca7-433c-8a05-a1a46872cc25.png">

**Comment by Yan-weihao** [comment]
> 
  background_colour = "Normal",
What value should I set this to?

**Comment by Yan-weihao** [comment]
> I've improved the warning message, let me know if it is still unclear :smile: 

How do I set up a highlight group with a background

**Comment by rcarriga** [comment]
You need to provide a colour to be used for when a window is fully transparent. True transparency is not possible in a terminal so it's faked by setting the window/text to the background colour. Whatever background colour you use for your terminal is a good choice. Looking at your dotfiles I can see you have it set to `0x282A36` so pass `#282A36` to the notify setup function

**Comment by Yan-weihao** [comment]
then how can i use in transparent window
nvim-notify

**Comment by Yan-weihao** [comment]
So how can I use nvim-notify in transparent window

**Comment by Yan-weihao** [comment]
The error exists no matter what value I set background_colour to

**Comment by Yan-weihao** [comment]
My notification background is already transparent, but it still warns me

<img width="960" alt="image" src="https://user-images.githubusercontent.com/61379647/172156515-13918ba8-085d-45d1-bf7f-3eba084512fa.png">

**Comment by Yan-weihao** [comment]
I changed the highlight group
<img width="952" alt="2022-06-06_20-01" src="https://user-images.githubusercontent.com/61379647/172156984-d6b4c921-cc89-4746-a86e-3d91f8b7b563.png">

**Comment by Yan-weihao** [comment]
> 


> 当窗口完全透明时，您需要提供一种颜色。真正的透明度在终端中是不可能的，因此它是通过将窗口/文本设置为背景颜色来伪造的。无论您为终端使用什么背景颜色都是不错的选择。查看您的点文件，我可以看到您已将其设置为`0x282A36`传递给通知设置功能`#282A36`

how should i use my own highlight group or what color should i give it

**Comment by rcarriga** [comment]
As stated in the warning, provide a colour to the setup
```lua
require("notify").setup({
  background_colour = "#282A36"
})
```

**Comment by rcarriga** [comment]
Can you show me exactly what you're providing to the setup?

**Comment by Yan-weihao** [comment]
> 
this is my config file

`local status_ok, notify =  pcall(require, "notify")
if not status_ok then
  vim.notify("notify module not found!")
  return
end

require("notify")("严伟浩欢迎你")
vim.notify = notify
require("notify").setup({
  active = true,
  on_config_done = nil,
  -- Animation style (see below for details)
  stages = "slide",
  -- Function called when a new window is opened, use for changing win settings/config
  on_open = nil,
  -- Function called when a window is closed
  on_close = nil,
  -- Render function for notifications. See notify-render()
  render = "default",
  -- Default timeout for notifications
  timeout = 1000,
  -- Max number of columns for messages
  max_width = nil,
  -- Max number of lines for a message
  max_height = nil,
  -- For stages that change opacity this is treated as the highlight behind the window
  -- Set this to either a highlight group, an RGB hex value e.g. "#000000" or a function returning an RGB code for dynamic values
  background_colour ="#282A36",
  -- Minimum width for notification windows
  minimum_width = 50,
  -- Icons for the different levels
  icons = {
    ERROR = "",
    WARN = "",
    INFO = "",
    DEBUG = "",
    TRACE = "✎",
  },
})
`

**Comment by Yan-weihao** [comment]
> 此行`require("notify")("严伟浩欢迎你")`您在设置之前发送通知，因此使用默认配置并触发警告。删除该行

thank you, i solved the problem，
