### ISSUE TITLE
Keep notifications open if neovim is idle

### ISSUE THREAD

**Issue by ten3roberts** [rcarriga/nvim-notify#106]
I am using this plugin to notify on successful builds, but for long builds i often tab out or leave neovim.

A feature which stops the notifications from going away if the user has not made any action, like insert mode or normal mode actions for a while.

This could be accomplished with a simple autocmd for CursorHold starting an async timer which completes and keeps notifications on screen after e.x 30 or 60 seconds.

**Comment by rcarriga** [comment]
You can supply `timeout = false` to disable the timeout and then handle the closing yourself. Use the `on_open` option to get the window ID.
