### ISSUE TITLE
Notifications are not showing

### ISSUE THREAD

**Issue by tiagaoalb** [rcarriga/nvim-notify#109]
#### - This is the files tree.
.
├── init.lua
├── lua
│   ├── barbar-config
│   │   └── init.lua
│   ├── lsp-config
│   │   ├── language-servers.lua
│   │   └── nvim-cmp.lua
│   ├── lualine-config
│   │   └── init.lua
│   ├── mappings
│   │   └── init.lua
│   ├── nvim-tree-config
│   │   └── init.lua
│   ├── packer-config
│   │   └── init.lua
│   ├── settings
│   │   └── init.lua
│   └── treesitter-config
│       └── init.lua
└── plugin
    └── packer_compiled.lua

`settings/init.lua`
```sh
local set = vim.opt

vim.notify = require("notify")

set.expandtab = true
set.smarttab = true
set.shiftwidth = 4
set.tabstop = 4

set.hlsearch = true
set.incsearch = true
set.ignorecase = true
set.smartcase = true

set.splitbelow = true
set.splitright = true
set.wrap = false
set.scrolloff = 5
set.fileencoding = 'utf-8'
set.termguicolors = true

set.relativenumber = true
set.cursorline = true

set.hidden = true
```

`packer-config/init.lua`
```sh
return require'packer'.startup(function()
    use 'wbthomason/packer.nvim'
    use 'navarasu/onedark.nvim'
    use { 'kyazdani42/nvim-tree.lua', requires = {'kyazdani42/nvim-web-devicons', }, tag = 'nightly' }
    use 'hrsh7th/nvim-cmp'
    use 'nvim-treesitter/nvim-treesitter-refactor'
    use { 'nvim-treesitter/nvim-treesitter', run = ':TSUpdate' }
    use 'windwp/nvim-autopairs'
    use 'romgrk/barbar.nvim'
    use 'nvim-lualine/lualine.nvim'
    use 'rcarriga/nvim-notify'
    use 'windwp/nvim-ts-autotag'

    -- LSP plugins
    use 'neovim/nvim-lspconfig'
    use 'williamboman/nvim-lsp-installer'
    use 'hrsh7th/cmp-nvim-lsp'
    use 'saadparwaiz1/cmp_luasnip'
    use 'L3MON4D3/LuaSnip'
    use 'onsails/lspkind.nvim'
    use 'iamcco/markdown-preview.nvim'
end)
```

`nvim/init.lua`
```sh
require('settings')
require('mappings')
require('packer-config')
require('onedark').load()
require('nvim-tree-config')
require('lsp-config.language-servers')
require('lsp-config.nvim-cmp')
require('lualine-config')
require('barbar-config')
require('treesitter-config')
```

**Comment by rcarriga** [comment]
Does anything happen if you run `require("notify").setup({})`?

Also what about `require("notify")("test")?

**Comment by tiagaoalb** [comment]
> Does anything happen if you run `require("notify").setup({})`?
> 
> Also what about `require("notify")("test")?

The first command returns nothing, but the second returns "test".

**Comment by rcarriga** [comment]
> but the second returns "test".

You mean a window pops up showing `test`?

**Comment by tiagaoalb** [comment]
> > but the second returns "test".
> 
> You mean a window pops up showing `test`?

Yes 😃, but when I install a new plugin it shows nothing.

**Comment by rcarriga** [comment]
What are expecting to see exactly? It looks like everything is working from nvim-notify
