### ISSUE TITLE
[Question] Does the `:Telescope notify` command still exist?

### ISSUE THREAD

**Issue by TornaxO7** [rcarriga/nvim-notify#111]
I can't execute `:Telescope notify` anymore and I can't see any changes in the README.md. What am I doing wrong?

**Comment by oeyoews** [comment]
@TornaxO7 [#ref](https://github.com/rcarriga/nvim-notify#:~:text=Note%3A%20If%20you%20lazy%20load%20telescope%20you%20should%20manually%20call%20require(%22telescope%22).load_extension(%22notify%22)%20before%20using%20the%20above%20commands.%20If%20you%20don%27t%20lazy%20load%20telescope%20then%20notify%20does%20this%20for%20you.)

**Comment by TornaxO7** [comment]
Oh, thank you
