### ISSUE TITLE
timeout=false has no effect

### ISSUE THREAD

**Issue by hassec** [rcarriga/nvim-notify#112]
Hi @rcarriga, 

I'm not sure what changed, but it seems like the option `timeout=false` isn't respected anymore. 

If I open neovim and just execute `:lua require'notify'("test", 'info',{timeout=false})` the popup will disappear after a short delay.  

Setting the timeout to a numeric value seems to work as expected, just the disabling via `=false` seems broken.

**Comment by rcarriga** [comment]
Thanks for the report! Should be working in latest commit
