### ISSUE TITLE
`Highlight group 'Normal' has no background highlight` error comes up every time there a message on start

### ISSUE THREAD

**Issue by ysfgrgO7** [rcarriga/nvim-notify#113]
![Screenshot_2022-07-07-01-31-59_1600x900](https://user-images.githubusercontent.com/94284073/177647142-519e53a5-e7f2-4863-9f9b-7664b1be317d.png)

**Comment by rcarriga** [comment]
I's instructing you on how to remove the message, add a background colour to the setup.
```lua
require("notify").setup({
  background_colour = "#000000",
})
```

**Comment by ysfgrgO7** [comment]
Thanks for your help
