### ISSUE TITLE
Can I set focusable=false to nvim-notify window?

### ISSUE THREAD

**Issue by kawarimidoll** [rcarriga/nvim-notify#119]
I often use [CTRL-W_CTRL-W](https://neovim.io/doc/user/windows.html#CTRL-W_CTRL-W) to change windows.
This sometimes focuses to nvim-notify window, but I don't want do so...
I think this will be fixed by setting `focusable=false` to the window.

Thank you for your nice plugin!

**Comment by rcarriga** [comment]
You can add an `on_open` wrapper 

```lua
  require("notify").setup({
    on_open = function (win)
      vim.api.nvim_win_set_config(win, { focusable = false })
    end,
  })
```

**Comment by kawarimidoll** [comment]
Thank you quick response, it works well 🥰
