### ISSUE TITLE
String cannot contain  newlines

### ISSUE THREAD

**Issue by Mte90** [rcarriga/nvim-notify#125]
![immagine](https://user-images.githubusercontent.com/403283/186135986-bd922d3c-841d-4724-b208-2aa55dee95a9.png)

As you can see...
It is possible to trim newlines to avoid this error?

**Comment by Mte90** [comment]
It is generated my guess from LSP using php actor but I am not sure what is the source...

**Comment by rcarriga** [comment]
I can see from the traceback that the call to `vim.notify` is within your own config in `.config/nvim/lua/plugin/lsp.lua`. Can you show what that LSP handler looks like?

**Comment by Mte90** [comment]
The snippet is the one on https://github.com/neovim/nvim-lspconfig/wiki/User-contributed-tips#use-nvim-notify-to-display-lsp-messages

my dot files: https://github.com/Mte90/dotfiles/blob/master/.config/nvim/lua/plugin/lsp.lua#L168

**Comment by rcarriga** [comment]
Aha yes that's it. It places it in a list for some reason. Just change `{ result.message }` to `result.message` and it'll work as expected

**Comment by Mte90** [comment]
Cool :-)
