### ISSUE TITLE
Notify level='DEBUG', 'TRACE' not producing notification window

### ISSUE THREAD

**Issue by timtro** [rcarriga/nvim-notify#126]
Thank you for your time and effort.

**THE ISSUE**
`:lua require'notify' ('Foo.', 'DEBUG' )` fails to produce a notification window, but the notification is logged and accessible via `:Telescope notify`. Any choice of `vim.log.levels.DEBUG`, `vim.lsp.log_levels.DEBUG` or the digit `1` for the level argument produces the same. The same is also true for variations of 'TRACE'.

**EXPECTED BEHAVIOUR**
Some sort of notification window. I could see this being the design, but I can't find anywhere in the source or documentation that suggests it is.

**VERSIONS & CONFIG**
- Running on
```
> lsb_release -a

No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy
```
- with neovim version:
```
> nvim --version

NVIM v0.8.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -ffile-prefix-map=/build/neovim-DFNyWP/neovim-0.8.0~ubuntu1+git202208232347-6cc6e1192-c99271b19=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-DFNyWP/neovim-0.8.0~ubuntu1+git202208232347-6cc6e1192-c99271b19/build/cmake.config -I/build/neovim-DFNyWP/neovim-0.8.0~ubuntu1+git202208232347-6cc6e1192-c99271b19/src -I/build/neovim-DFNyWP/neovim-0.8.0~ubuntu1+git202208232347-6cc6e1192-c99271b19/.deps/usr/include -I/usr/include -I/build/neovim-DFNyWP/neovim-0.8.0~ubuntu1+git202208232347-6cc6e1192-c99271b19/build/src/nvim/auto -I/build/neovim-DFNyWP/neovim-0.8.0~ubuntu1+git202208232347-6cc6e1192-c99271b19/build/include
Compiled by buildd@lcy02-amd64-074

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- `nvim-notify` installed with packer from current master.
- No additional configuration of `nvim-notify`
- Tested without colourschemes.
- Nothing in checkhealth that sends any red-flags.
- `:lua vim.notify(vim.inspect(vim.log.levels))` produces
    {
      DEBUG = 1,
      ERROR = 4,
      INFO = 2,
      OFF = 5,
      TRACE = 0,
      WARN = 3
    }  
- `:lua vim.notify(vim.inspect(vim.lsp.log_levels))` produces
    { "DEBUG", "INFO", "WARN", "ERROR", "OFF",
      [0] = "TRACE",
      DEBUG = 1,
      ERROR = 4,
      INFO = 2,
      OFF = 5,
      TRACE = 0,
      WARN = 3
    }

**Comment by rcarriga** [comment]
You're looking for the `level` config option, see `:h notify.config`

**Comment by timtro** [comment]
> You're looking for the `level` config option, see `:h notify.config`

Oh, for goodness sake. Thank you. I am sufficiently embarrassed to have not seen that either in the documentation or the code. And on the principle that “I'm rarely the first person to notice a bug and file,” I knew it was probably something obvious I was missing.

Thanks again.

And thanks for all your work.
