### ISSUE TITLE
error running notification service

### ISSUE THREAD

**Issue by max397574** [rcarriga/nvim-notify#128]
Error running notification service: ...opt/nvim-notify/lua/notify/service/buffer/highlights.lua:118: a
ttempt to call method '_get_hl_from_capture' (a nil value)

**Comment by folke** [comment]
Any chance you're using Tokyonight? I merged some PR's yesterday and one of them caused this issue for me. Fixed my issue already on Tokyonight.

The cause for me was `TelescopeNormal` having `None` as bg.

**Comment by rcarriga** [comment]
It's due to a breaking change in nightly, should be working now :smile:
