### ISSUE TITLE
notify is expecting a maximum of only 2 arguments

### ISSUE THREAD

**Issue by heygarrett** [rcarriga/nvim-notify#130]
The docs say the notify function takes 1-3 arguments (`msg`, `level` and `opts`), but [lua-language-server](https://github.com/sumneko/lua-language-server) is giving me a warning and says the function only takes 2 arguments:  
<img width="1025" alt="Screen Shot 2022-09-14 at 14 13 44" src="https://user-images.githubusercontent.com/1154912/190231740-91d31392-fd2f-4f07-a699-0e96fa5e437c.png">

```
NVIM v0.8.0-dev-2548-gbf6de51f5-dirty
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by garrett@Garretts-MacBook-Pro.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-bf6de51_1/share/nvim"

Run :checkhealth for more info
```

**Comment by rcarriga** [comment]
AFAIK the Lua LS is not smart enough to infer the types of the module so it's likely from a type file you have from another plugin like lua-dev.nvim. If you use goto definition it should show where the type is defined.

**Comment by heygarrett** [comment]
>  If you use goto definition it should show where the type is defined.

It appears to be getting the definition from here:
https://github.com/williamboman/mason.nvim/blob/main/lua/mason-core/notify.lua

I have no idea how to rectify that. 🤔 Thanks though!
