### ISSUE TITLE
require returning boolean instead of "table"

### ISSUE THREAD

**Issue by okuma10** [rcarriga/nvim-notify#133]
Don't know anything about lua. But apparently when calling `require` I should be getting a "table" object, but I'm not
:lua print(require('notify')) - > `true`
:lua print(pcall(require, 'notify')) -> `true` `true`
:lua print(require('alpha')) -> `table:<address>`
:lua print(pcall(require, 'alpha')) -> `true` `table:<address>`

**Comment by rcarriga** [comment]
This is probably a local path issue. I'd recommend checking your runtime path for modules named `notify`. If you can't find the issue, please provide a minimal init.lua to reproduce

**Comment by okuma10** [comment]
Ah, I see yes I had a folder named `notify` in my Lua settings folder. It had the `notify` setup in init.lua. but I since removed it and add the setting under a /user/ folder(following a setup tutorial). I removed the old folder and now it loaded just fine.
Thanks!
