### ISSUE TITLE
attempt to index field 'title' (a number value)

### ISSUE THREAD

**Issue by Kohirus** [rcarriga/nvim-notify#136]
I use [mason.nvim](https://github.com/williamboman/mason.nvim) to install LSP servers, DAP servers, linters, and formatters. After I started Neovim, then I type `:Mason` command to open Mason's window, When the installed server package check update was complete, I received the following error message:

```
Error executing vim.schedule lua callback: ...k/packer/start/nvim-notify/lua/notify/render/default.Lua:9:attempt to index field 'title'(a number value)
stack traceback:
...k/packer/start/nvim-notify/lua/notify/render/default.Lua:9:in function 'render'
...ker/start/nvim-notify/lua/notify/service/buffer/init.Lua:102:in function 'render'
..ack/packer/start/nvim-notify/lua/notify/service/init.Lua:53:in function push'
...m/site/pack/packer/start/nvim-notify/lua/notify/init.Lua:214:in function 'notify'
...m/site/pack/packer/start/nvim-notify/Lua/notify/init.Lua:275:in function <...m/site/pack/packer/start/nvimnotify/lua/notify/init.Lua:274>
```

The screenshot is as follows：

![question1](https://user-images.githubusercontent.com/45937428/192704875-42eb96a1-e2b1-4457-b35f-514e4b0d2119.png)

Then i type `Enter` to continue:

![question2](https://user-images.githubusercontent.com/45937428/192705076-1dbbf1da-2a49-4712-99fe-d89d888c94d2.png)

**Comment by rcarriga** [comment]
This is likely a bad notification being called with a number title. I've added a validation check so you'll get a strack trace with the location of where it's called now

**Comment by Kohirus** [comment]
The screenshot is as follows：
![question3](https://user-images.githubusercontent.com/45937428/192771626-015dbf44-e08e-40e9-9473-43f004e119d6.png)

**Comment by rcarriga** [comment]
I took a look and your dotfiles define a global `error` function. This overrides the builtin in `error` function which is used by a lot of code. Don't do this. In general avoid defining globals unless they have very specific names that are not going to be used by anything else

**Comment by Kohirus** [comment]
Now the plugin works properly！Thank you！I will close the issue.
