### ISSUE TITLE
[feat]: gap between notifications

### ISSUE THREAD

**Issue by kaiphat** [rcarriga/nvim-notify#138]
Add opportunity to set gap between notifications in this case

**Comment by kaiphat** [comment]
![image](https://user-images.githubusercontent.com/53742299/193997550-8dd4ba35-1d33-43c5-b77c-d169d0d775fe.png)

**Comment by rcarriga** [comment]
You can write a custom set of animation stages to do this

**Comment by kaiphat** [comment]
Thank you!
