### ISSUE TITLE
Feature request: add animate=false

### ISSUE THREAD

**Issue by folke** [rcarriga/nvim-notify#140]
Hi!

Within [Noice](https://github.com/folke/noice.nvim) I currently use the global notify instance for most messages, but I use a separate instance for messages that need to be shown during a blocking event.

It works as is, but it's far from perfect. Biggest problem is that messages from the two instances can overlap.

Better would be that I could use the same global instance everywhere, but pass in something like `animate=false` as an option to `vim.notify`.

Not sure what the best way would be to implement this and if you think `animate=false` is a good name for this.

What I think it should do, is propagate some animation properties instantly to 100%? Any ideas?

**Comment by rcarriga** [comment]
I think this makes sense and see no issue with the parameter name. There may be some complications around advancing to the stage which is "visible" (i.e. has a `time` setting) synchronously. I'll have to put some time into the solution

**Comment by rcarriga** [comment]
OK I've got an `animate` parameter in #149 which should do what you were looking for. Please try it out and let me know :smile:

**Comment by folke** [comment]
Sweet! I'm on a vacation right now (without laptop), but will definitely check it out once I'm back. Thanks!

**Comment by rcarriga** [comment]
Cool no rush! Enjoy your holiday :smile:
