### ISSUE TITLE
Show notifications at the bottom of the window

### ISSUE THREAD

**Issue by aloussase** [rcarriga/nvim-notify#141]
Hi, I love this plugin but the notifications appearing at the top of the window have been bugging me for some time.

Every time I open a file in NvimTree I get a notification that doesn't let me see anything in the
file tree (I use it at the right). I can set the timeout option to a low value, but that doesn't feel clean. 

Is there a way to show the notiifcation at the bottom-right of the screen instead of the
top-right?

**Comment by rcarriga** [comment]
See `top_down` parameter for setup `:h notify.config`
