### ISSUE TITLE
non-float cannot have 'row'

### ISSUE THREAD

**Issue by AntPeixe** [rcarriga/nvim-notify#144]
I'm running nvim 0.8 and just installed this plugin.

When multiple notifications are present this error appears after the first is removed. When this happens the remaining notifications aren't cleared.

Error message: `...ack/packer/start/nvim-notify/lua/notify/windows/init.lua:285: non-float cannot have 'row'`

I think this is related to #105 as it seems to happen when the remaining notifications would move up.
I've tried changing the animation to `slide` which shouldn't have the above feature by default and the issue stops happening.

Please let me know if you need any extra info.

**Comment by rcarriga** [comment]
Thanks for the report. Due to previous commit, should be working now in latest master 😄

**Comment by AntPeixe** [comment]
Updated and seems to be fixed :+1:
