### ISSUE TITLE
Pressing `q` with active notification popups behaves differently than normally

### ISSUE THREAD

**Issue by msva** [rcarriga/nvim-notify#147]
Hi there!

I've suddenly found that when I press `q` while there is notification popup visible, nvim quits immediately.
While "normally" `q` is bound to `:Sayonara`, and "normal" behaviour is "if there are any buffers except current, just close it, and if it is latest buffer - quit".

I'm not sure how exactly that happens (I didn't found any remaps in nvim-notify code), but it is pretty strange that behaviour of `q` key differs between states when there is "active" notifications and when there isn't.

Can you help me to debug (and, ideally, fix) this issue, please?

**Comment by rcarriga** [comment]
As you said, nvim-notify doesn't map anything so it's most likely an issue with the other plugin. I'm not going to debug an issue that's likely with another plugin so I'd suggest debugging yourself or opening an issue in that repo and seeing if they have any ideas

**Comment by msva** [comment]
Well, I suppose that this works like that: nvim-notify creates a buffer for displayed text and use it for content of the popup.
And, possibly, when sayonara tries to analyze if current buffer belongs to any window, and whether that window have another listed buffers, it softfails, that leads to the decision that there is no more listed buffers.

But I don't yet analyzed code of both nvim-notify and sayonara enough to confirm this idea.

And yes, probably this should be fixed on sayonara side, if that idea would be confirmed, but as it is related to nvim-notify behaviour, I'd like to notice @mhinz attention to `nvim-notify`,

**Comment by msva** [comment]
(closing as it is not nvim-notify issue)
