### ISSUE TITLE
feat: Keep a log the notifications so they can be checked later

### ISSUE THREAD

**Issue by shadmansaleh** [rcarriga/nvim-notify#15]
Default `vim.notify` writes the notifications to message buffer . You can later check what were the issues later .

I think nvim-notify should log them in a buffer and provide a command that open in a split.

It should be really easy you'll just have to store all the notifications in an list and when user calls the command make a scratch buffer out of then and display it.

It's will be pertucularly useful for debugging plugin errors at startup.

**Comment by jdhao** [comment]
Related to #11.

**Comment by rcarriga** [comment]
I've merged in changes to expose the previous messages `notify.history()`, which can be used to construct a buffer or however else you want to view them

**Comment by shadmansaleh** [comment]
Thanks. A built-in implementation will definitely be useful :)

**Comment by shadmansaleh** [comment]
@rcarriga notify.history() should store other opts too I think . For example tittle .

**Comment by jdhao** [comment]
> I've merged in changes to expose the previous messages `notify.history()`, which can be used to construct a buffer or however else you want to view them

Thanks, works for me.

**Comment by rcarriga** [comment]
> Thanks. A built-in implementation will definitely be useful :)

Yep I'll work on getting helpers built-in to use with buffers, telescope etc but there were several people requesting this so thought it would be better to get something first :smile: 

> notify.history() should store other opts too I think . For example tittle .

Good point, I'll add title to it :ok_hand:
