### ISSUE TITLE
Notifications cannot slide out

### ISSUE THREAD

**Issue by Lraxer** [rcarriga/nvim-notify#154]
Hello, I'm using https://github.com/ayamir/nvimdots as my config, and when I set `stages="slide"`, the notification cannot slide out when it reaches the timeout. Also the popup window looks like it is stuck, just as #152. I have to generate another notification to make the former stay in the right position. Please check the following gif.

<img src="https://user-images.githubusercontent.com/32860114/200737197-5e72d870-a3d5-4ebf-980d-88f98fcc5cf4.gif" width="700"/>

You can see that only I generate a new one, those already-reached-timeout notifications can slide out, and there is also some padding issues. 

The `fade_in_slide_out` option does not have this bug. I test v3.7.3, `stages = slide` works normally. So I think it is not my config issue, maybe someone can reproduce it?

I'm using archlinux, kitty, neovim v0.8.0, here is my configuration.

```lua
notify.setup({
	---@usage Animation style one of { "fade", "slide", "fade_in_slide_out", "static" }
	stages = "slide",
	---@usage Function called when a new window is opened, use for changing win settings/config
	on_open = nil,
	---@usage Function called when a window is closed
	on_close = nil,
	---@usage timeout for notifications in ms, default 5000
	timeout = 2000,
	-- Render function for notifications. See notify-render()
	render = "default",
	---@usage highlight behind the window for stages that change opacity
	background_colour = "Normal",
	---@usage minimum width for notification windows
	minimum_width = 50,
	---@usage notifications with level lower than this would be ignored. [ERROR > WARN > INFO > DEBUG > TRACE]
	level = "TRACE",
	---@usage Icons for the different levels
	icons = {
		ERROR = icons.diagnostics.Error,
		WARN = icons.diagnostics.Warning,
		INFO = icons.diagnostics.Information,
		DEBUG = icons.ui.Bug,
		TRACE = icons.ui.Pencil,
	},
})
```

**Comment by rcarriga** [comment]
Thanks for the report! Should be working in master again :smile:

**Comment by Lraxer** [comment]
I test the the latest version, now the bug is fixed, thank you!
