### ISSUE TITLE
transparent background color notification

### ISSUE THREAD

**Issue by uloco** [rcarriga/nvim-notify#159]
I am a theme author and currently puzzled how I could set the background_color property for a user if my theme has a transparent background. 

I am overriding the following hl groups

```
NotifyERRORBody
NotifyWARNBody
NotifyINFOBody
NotifyDEBUGBody
NotifyTRACEBody
```

Is there a way to do this from a theme side? Or does every notify user then need to do this? What if they switch their theme often from light to dark?

Also is there a way to disable the notification, since the defaults maybe ok anyway?

**Comment by rcarriga** [comment]
I've changed it to use a `NotifyBackground` group instead of `Normal` by default so you can provide an background for that highlight in your theme

**Comment by uloco** [comment]
Works like a charm thank you so much for this!
