### ISSUE TITLE
Highlight group 'Normal' has no background highlight.

### ISSUE THREAD

**Issue by danielnehrig** [rcarriga/nvim-notify#16]
on notify.nvim start i get

```
Highlight group 'Normal' has no background highlight.

Please provide an RGB hex value or highlight group with a background value for 'background_colour' option

Defaulting to #000000
Press ENTER or type command to continue
```

and then a loop of
```
NotifyLOGIcon16 xxx links to NotifyLOGIcon
NotifyLOGTitle16 xxx links to NotifyLOGTitle
NotifyLOGBorder16 xxx links to NotifyLOGBorder
NotifyLOGBody16 xxx links to NotifyLOGBody
Press ENTER or type command to continue
```
this error makes the plugin unusable to me

i use a transparent colorscheme which has no normal color

**Comment by rcarriga** [comment]
There are two separate issues happening here.

The first is that you haven't set a window background colour for use with opacity changing. You can follow the instructions to set `background_colour` in the setup config to a different highlight group or an RGB hex value to use instead. Alternatively if you don't want to use opacity animations, change your `stages` config value to `slide` or `static`

The second issue is that it looks like you're passing an unknown `log` level to the function and so the highlights are not defined. You can work around this by defining the groups
```
NotifyLOGIcon
NotifyLOGTitle
NotifyLOGBorder
NotifyLOGBody
```
however I'll likely add a fallback to use `INFO` highlights to avoid the blocking error

**Comment by danielnehrig** [comment]
alright thanks for the info

**Comment by rcarriga** [comment]
I've added a fallback mechanism for highlights so you won't have the spamming issue anymore
