### ISSUE TITLE
How can I use nvim-notify in coc.nvim?

### ISSUE THREAD

**Issue by yingmanwumen** [rcarriga/nvim-notify#160]

**Comment by rcarriga** [comment]
I don't use coc.nvim but there are some recipes in the wiki https://github.com/rcarriga/nvim-notify/wiki/Usage-Recipes

**Comment by yingmanwumen** [comment]
> I don't use coc.nvim but there are some recipes in the wiki https://github.com/rcarriga/nvim-notify/wiki/Usage-Recipes

Thanks vary much!
