### ISSUE TITLE
Use of vim.lsp.log_levels

### ISSUE THREAD

**Issue by aloknigam247** [rcarriga/nvim-notify#161]
I was trying to optimise my configs for minimal time and lazy loaded all my lsp plugins to load only for filetype whose lsp  server are installed.

I found that nvim-notify depends on vim.lsp and increases load time.

Instead of using vim.lsp.log_levels, vim.lo.levels can be used which is faster and dependency free.

Also the table retruned by vim.lsp.log_levels and vim.log.levels are almost identical.

**Comment by rcarriga** [comment]
Replaced all usage of `vim.lsp.log_levels` :+1:

**Comment by rcarriga** [comment]
Missed a conversion, should be fixed in master now

**Comment by ievgenii-shepeliuk** [comment]
Confirmed, it works. Thanks.

**Comment by MichaelPetersen22** [comment]
That means this can be closed now right?

**Comment by ievgenii-shepeliuk** [comment]
from my side, it worked.
