### ISSUE TITLE
[Question] highlight text when render is minimal

### ISSUE THREAD

**Issue by jyf-111** [rcarriga/nvim-notify#168]
```lua
require("notify").setup({
			stages = "fade",
			timeout = 1000,
			top_down = true,
			max_width = 32,
                        animation = false
		})
vim.api.nvim_set_hl(0, "NotifyINFOIcon", { fg = "gray" })
require("notify")({"some text"},"info",{render = "minimal"}
```
when render is minimal, text highlight is `NotifyINFOIcon`, is it correct? i think make it be `NotifyINFOBody` or `NotifyINFOTitle` is better

---
result highlight `NotifyINFOIcon`:
<img width="365" alt="image" src="https://user-images.githubusercontent.com/77335030/213965716-6f42d709-e017-4dcb-8852-fe4234425243.png">

**Comment by rcarriga** [comment]
The icon and title highlight are the same by default so icon makes as much as sense as title. Body is the same across all levels so wouldn't work. 

Easiest solution is to define the icon highlights how you'd like them. Alternatively check out the `compact` view

**Comment by jyf-111** [comment]
got it，thanks
