### ISSUE TITLE
The coc I use, how to update the status like lsp？

### ISSUE THREAD

**Issue by xinghe98** [rcarriga/nvim-notify#172]
your wiki
![](https://user-images.githubusercontent.com/24252670/152641078-92f3da72-f49f-4705-aec8-86512693445f.gif)

my setting

![](https://i.328888.xyz/2023/01/28/j7WKH.gif)

**Comment by rcarriga** [comment]
I don't use coc but it looks like someone has already posted a recipe for it https://github.com/rcarriga/nvim-notify/wiki/Usage-Recipes#cocnvim-integration---status-and-diagnostics
