### ISSUE TITLE
question: Can the notification window be exempt from selecting a window?

### ISSUE THREAD

**Issue by matoous** [rcarriga/nvim-notify#18]
Hello! I am not sure how to correctly formulate the question so I will try with an example that lead me to this:

When there's an open notification and I want to open a file from `nvim-tree` I am asked to select a window I want to open the file in. I see only `A` for the main window but when I tried pressing `B` to test it out, the buffer get's opened in a notification window.

I tried googling around and maybe this is partially similar issue: https://github.com/liuchengxu/vim-clap/issues/139 or this one https://github.com/junegunn/fzf/issues/453. Reading those it seems, there's not an optimal solution. Either way, I just wanted to try and ask here, maybe some will have an idea.

Feel free to close this if you want to as it is related to usage of another plugin and I in general have a feeling that maintainers shouldn't be bothered with those.

**Comment by rcarriga** [comment]
Ah thanks for reporting, hadn't actually noticed this. I've added a filetype `notify` to the buffers so you can use the following setting  to exclude it from nvim-tree
```lua
vim.g.nvim_tree_window_picker_exclude = {
  filetype = {
    "notify",
  }
}

```
