### ISSUE TITLE
CTRL-W_W moves to the notification window

### ISSUE THREAD

**Issue by riton** [rcarriga/nvim-notify#183]
Hi,

## Question

I've just switched to [lazyvim that bundles your plugin with this configuration](https://www.lazyvim.org/plugins/ui#nvim-notify).

I was previously used to rely on `CTRL-W_W` to move between windows.

My problem is that it seems that the _notification window_ is also a _real vim window_ . Resulting in the `CTRL-W_W` _shortcut_ often moving my _cursor_ to the _notification window_ instead of my _other buffer window_ when a notification is displayed.

I've tried to make a little video to illustrate that:

https://user-images.githubusercontent.com/553730/223159300-ec546d9e-5bab-49e3-8b3e-edfe56eb4e70.mp4

In the last seconds of the video, you should see that the _vim cursor_ is in the _notification window_ .

I'm kinda lost. Is there any workaround ? Should I use another _shortcut_ to move between windows ?

Thanks in advance for your help !

Regards

## Software versions

* `nvim-notify` at commit `281e4d793c550c866bea3fb85d39de1f0188fb50`

```
❯ nvim --version
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az190-151
```

**Comment by rcarriga** [comment]
You can disable focusing on the window with the `on_open` setup option
```lua
    on_open = function(win)
      vim.api.nvim_win_set_config(win, { focusable = false })
    end,
```

**Comment by riton** [comment]
This just works ! Thanks @rcarriga 

Regards

**Comment by Galicarnax** [comment]
I suggest this should be mentioned in `README` and/or `:h notify`.
