### ISSUE TITLE
Question: close notification with keymap

### ISSUE THREAD

**Issue by yriveiro** [rcarriga/nvim-notify#187]
Can I close a notification using a keymap without waiting for the TTL of the notification to close it?

I'm using [Noice.nvim](https://github.com/folke/noice.nvim) which uses notify underneath. Sometimes, notifications are too big and I would like to close them without waiting for the TTL to kick in.

Is this possible using a keymap or some kind of custom code?

**Comment by rcarriga** [comment]
You can use `notify.dismiss()` :smile:

**Comment by yriveiro** [comment]
Ok, I was looking using the word `close` and I only found the `on_close`, my bad I was not looking the right way. Thanks for the help!
