### ISSUE TITLE
Disable the notification on save

### ISSUE THREAD

**Issue by Xiaobo2020** [rcarriga/nvim-notify#190]
Hi. As described in the title, can I disable notifications for saved actions? e.g. `:w`

**Comment by rcarriga** [comment]
nvim-notify doesn't send any notifications, other plugins do. The saved message is from noice.nvim, you might be able to configure it prevent certain messages or you can do something like this https://github.com/rcarriga/nvim-notify/issues/114#issuecomment-1179754969
