### ISSUE TITLE
Is there a simple way to configure the animation speed?

### ISSUE THREAD

**Issue by Hubro** [rcarriga/nvim-notify#194]
With the default animations, I sometimes miss that there is a notification because it fades in so gently. I've set `stages = "slide"` so it always slides in and out, but now it slides in so slowly that I often end up waiting for the animation finishes so I can see the text.

Is there a simple way I can reduce the total animation time by 25-50%? I just want the total animation time to be somewhere around 100-200 ms so the animation always finishes before I have time to look over. Currently it feels like it takes something like 400-500ms, which feels a smidge too slow for my taste.

**Comment by rcarriga** [comment]
All of the animation can completely customised by writing your own stages. You can use one of the existing ones and tweak the parameters as described here https://github.com/rcarriga/nvim-notify#changing-the-window. You're looking for `damping` and `frequency` in particular
