### ISSUE TITLE
Move the window position

### ISSUE THREAD

**Issue by FZZkill** [rcarriga/nvim-notify#197]
For example. 
![image](https://github.com/rcarriga/nvim-notify/assets/76607157/124d09f2-1e26-4799-aa16-824699dc4af7)
It will be in the upper right corner and will block my directory tree (or something, the contents of the second window.)
Is there a way for me to make it appear somewhere else? For example, the bottom right corner. :-)

**Comment by rcarriga** [comment]
Add `top_down = false` to your setup table, otherwise for further customisation you can write custom stages (see https://github.com/rcarriga/nvim-notify#animation-style)

**Comment by tf42src** [comment]
New to neovim and lua, @rcarriga can you show an example?

My attempt looks like this:

![Screenshot from 2024-06-01 18-23-26](https://github.com/rcarriga/nvim-notify/assets/9712861/7ac87fa8-553e-4db3-9ac6-3c964d2219ca)

**Comment by jaskerv** [comment]
@LzzKill 
Did you manage to configure it to the left side? If so could you kindly share your config 🙏🏻

**Comment by LzzKill** [comment]
Sorry, I unknown how to configure it to the left side. I only move it to right-down from right-up.
