### ISSUE TITLE
Other animation style

### ISSUE THREAD

**Issue by michaelb** [rcarriga/nvim-notify#2]
It'd be nice to have other animations available, such as fade-in/out like demonstrated in https://neovim.discourse.group/t/wip-animated-notifications-plugin/448

**Comment by rcarriga** [comment]
Yep I'd like to make the animations customisable and perhaps supply pre-packaged configs depending on how complex it will be. Have to figure out an API for it first!

**Comment by figsoda** [comment]
no animation would be nice too

**Comment by rcarriga** [comment]
Closing this thread as it looks like all requests are resolved
