### ISSUE TITLE
Option to configure border style?

### ISSUE THREAD

**Issue by samtgarson** [rcarriga/nvim-notify#201]
Hello, thanks for the great plugin.

I'd like to customise the border style of the messages but otherwise leave everything as is—I think right now I'd need to provide an entire set of stages functions just to do this.

Would you consider an option to provide a top-level customisation for [this setting](https://github.com/rcarriga/nvim-notify/blob/master/lua/notify/stages/fade.lua#L18) in the built-in styles? If so, I'd be happy to submit a PR. Thanks!

**Comment by Hoohan** [comment]
Hi! 

I was also finding a way to customize border style and then found that I need to write stages functions. I am a totally beginner to use nvim-notify. Maybe this is not beginner-friendly? I support that a top-level customization for border is necessary.

I would appreciate it if you could submit a PR. Thanks!

**Comment by JustasPolis** [comment]
You can override config with on_open callback in config.

```
on_open = function(win)
          local config = vim.api.nvim_win_get_config(win)
          vim.api.nvim_win_set_config(win, config)
end
```

**Comment by rcarriga** [comment]
As stated by @JustasPolis, window config can be done using the on_open callback
