### ISSUE TITLE
Option to Interrupt Timeout & Close via Keymap

### ISSUE THREAD

**Issue by dboyd42** [rcarriga/nvim-notify#203]
Trying to close the notification's popup manually before the timeout. The timeout doesn't need to be changed as (personally) the default 5 seconds works great. However, when either a notification is "blocking" text or the notification is repeated from a previous session; I'd just like to close the popup.

Any help would be appreciated. Thanks in advanced!

**Comment by NStefan002** [comment]
I wanted to clear all notifications when I enter insert mode, so I created the following autocmd:
```lua
            vim.api.nvim_create_autocmd({ "InsertEnter" }, {
                group = vim.api.nvim_create_augroup("NotifyClearGrp", {}),
                pattern = "*",
                callback = function()
                    require("notify").dismiss({ silent = true })
                end
            })

```
You could also bind this to some keymap like:
```lua
 vim.keymap.set('mode', 'some_key_kombo', function() require("notify").dismiss({ silent = true }) end, opts) 
 ```
Note that this clears all popups. I hope this was helpful.

**Comment by dboyd42** [comment]
@NStefan002 Yes, and thank you! I was previously looking at the `on_close` function rather than the `dismiss` --hence, why my config wasn't working.
