### ISSUE TITLE
Record level is incorrect

### ISSUE THREAD

**Issue by gadefox** [rcarriga/nvim-notify#206]
Any idea why the message type (record.level) is incorrect [here](https://pasteboard.co/9WW2aM3eLqu8.png)?

1. open new `nvim` instance
2. exec `:PackerUpdate`
3. try to save the file (`:w`)

**Comment by wookayin** [comment]
Image Not Found. please upload the attachment through Github directory. And you should also have a proper repro.

**Comment by gadefox** [comment]
```
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.1692716794
```
![notify](https://github.com/rcarriga/nvim-notify/assets/87468088/6579031b-b102-4a27-937b-75c1a26c14b2)

**Comment by rcarriga** [comment]
Closing as no reproduction given and the error just looks like noice.nvim is sending a level different to what you expect
