### ISSUE TITLE
Saving same buffer multiple times gives err

### ISSUE THREAD

**Issue by niksingh710** [rcarriga/nvim-notify#213]
![image](https://github.com/rcarriga/nvim-notify/assets/60490474/c2a25be2-9a43-4182-a5d2-0d8794c681b7)

**Comment by rcarriga** [comment]
nvim-notify doesn't send notifications, something else does. You can figure out what with something like this
```lua
local notify = require("notify")

vim.notify = function(...)
  print(debug.traceback())
  notify(...)
end
```

**Comment by niksingh710** [comment]
> nvim-notify doesn't send notifications, something else does. You can figure out what with something like this
> 
> ```lua
> local notify = require("notify")
> 
> vim.notify = function(...)
>   print(debug.traceback())
>   notify(...)
> end
> ```

can you please elaborate a bit as i am unable to go to the root of the problem.
and yeah it is not happening on nvim-notify but if i have nay kind of notification plugin. like nui or something
