### ISSUE TITLE
Enhancement: Add margin to the notification OR notification placement

### ISSUE THREAD

**Issue by cooperuser** [rcarriga/nvim-notify#22]
First of all, amazing plugin! The animations are so smooth!

Currently, the right side of the notification popup is right up against the edge of my terminal window. I would like to be able to specify how many columns it leaves in between the notification window and the edge.

Better yet (and I am assuming this is already planned for...), being able to control where the popup is. i.e.

top_left | top_center | top_right
:-|:-:|-:
**left** | **center** | **right**
**bottom_left** | **bottom_center** | **bottom_right**

If I find the time I could implement these things myself, but I'm rather busy atm. Thanks!

**Comment by rcarriga** [comment]
Thanks for the feedback, glad you like it :smile: 

So there is already the ability to completely change everything (placement, movement direction, opacity, speed etc) about the windows using custom animation stages (See the README for instructions).

The problem with changing the placement is that it requires changing how the windows are moved and coordinate with each other. I've abstracted this to be fairly simple (IMO of course!) and you can see examples in the built in stages. Here is the default: https://github.com/rcarriga/nvim-notify/blob/master/lua/notify/stages/fade_in_slide_out.lua.

Happy to offer assistance if something is not clear in the instructions, haven't had much feedback on it so not sure how helpful they are.

**Comment by Hubro** [comment]
I was also hoping to add 1 row of extra spacing between the bottom of my editor and the notifications, as they overlap the status bar in an extremely unsatisfying way that slightly annoys me dozens of timer per day :sweat_smile: 

![image](https://github.com/rcarriga/nvim-notify/assets/597206/931ea7d3-8acb-46af-bff7-361facd2b222)

**Comment by rperryng** [comment]
@Hubro I had the same need.  I usually use `opts = { stages = 'fade' }`, and my notifications were drawing over my `winbar`.  I was able to add a "margin" by basically duplicating the [existing `fade` configuration](https://github.com/rcarriga/nvim-notify/blob/d333b6f167900f6d9d42a59005d82919830626bf/lua/notify/stages/fade.lua) and just incrementing (or decrementing if you use `DIRECTION.BOTTOM_UP`) the `next_row` value if its the first window.  My full `notify` config looks like:

```lua
local MARGIN_VERTICAL = 1

local function fade_with_margin(direction)
  local stages_util = require('notify.stages.util')
  direction = direction or stages_util.DIRECTION.TOP_DOWN
  return {
    function(state)
      local next_height = state.message.height + 2
      local next_row = stages_util.available_slot(
        state.open_windows,
        next_height,
        direction
      )
      if not next_row then
        return nil
      end

      -- Add a margin if this is the "first" notification
      local is_first_window = #state.open_windows == 0
      if (is_first_window) then
        if direction == stages_util.DIRECTION.TOP_DOWN then
          next_row = next_row + MARGIN_VERTICAL
        elseif direction == stages_util.DIRECTION.BOTTOM_UP then
          next_row = next_row - MARGIN_VERTICAL
        end
      end

      return {
        relative = 'editor',
        anchor = 'NE',
        width = state.message.width,
        height = state.message.height,
        col = vim.opt.columns:get(),
        row = next_row,
        border = 'rounded',
        style = 'minimal',
        opacity = 0,
      }
    end,
    function()
      return {
        opacity = { 100 },
        col = { vim.opt.columns:get() },
      }
    end,
    function()
      return {
        col = { vim.opt.columns:get() },
        time = true,
      }
    end,
    function()
      return {
        opacity = {
          0,
          frequency = 2,
          complete = function(cur_opacity)
            return cur_opacity <= 4
          end,
        },
        col = { vim.opt.columns:get() },
      }
    end,
  }
end

return {
  {
    'rcarriga/nvim-notify',
    config = function()
      local stages_util = require('notify.stages.util')
      require('notify').setup({
        timeout = 1500,
        stages = fade_with_margin(stages_util.DIRECTION.TOP_DOWN),
      })
    end,
  },
}
```


![image](https://github.com/user-attachments/assets/8983f5c2-8a6a-4f02-b8a5-72984fa2befa)

---

@rcarriga thanks for your work, it was quite easy to extend as you suggested.  I did struggle a bit to understand what some of these stage values should be, (e.g. `relative` and `anchor`), are these options documented somewhere?  I couldn't tell from the `README.md` or help docs
