### ISSUE TITLE
How to disable nvim-notify on buffer write?

### ISSUE THREAD

**Issue by xbladesub** [rcarriga/nvim-notify#220]
I want to disable popups on buffer write - if I use keymap to save buffer I'm getting 1 successful popup and 1 error. If I use `:w` command manually - all good...
<img width="348" alt="image" src="https://github.com/rcarriga/nvim-notify/assets/45129790/27451235-87b1-4fbb-8b49-bfe6b9275e1a">

**Comment by xbladesub** [comment]
found it
```lua
  require("noice").setup({
    routes = {
      {
        filter = {
          event = "msg_show",
          kind = "",
          find = "written",
        },
        opts = { skip = true },
      },
    },
  })
  ```

**Comment by rcarriga** [comment]
Duplicate of #215
