### ISSUE TITLE
Examples don't work 

### ISSUE THREAD

**Issue by Zardoz89** [rcarriga/nvim-notify#222]
I have installed rcarriga/nvim-notify using Plug on neovim 0.7.2 and the examples don't work : 

![imagen](https://github.com/rcarriga/nvim-notify/assets/888483/2d46940e-7823-42df-8517-0d36e3d83056)
![imagen](https://github.com/rcarriga/nvim-notify/assets/888483/25e6311d-b8a4-4635-b9dc-9a087aa86ec7)
![imagen](https://github.com/rcarriga/nvim-notify/assets/888483/c9436e30-c2bf-4134-aa10-eca0282b4f2e)

Error E492 : It isn't an editor order : require("notify")("caca")

----

❯ nvim --version 
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compilado por team+vim@tracker.debian.org

Features: +acl +iconv +tui

**Comment by rcarriga** [comment]
You're running vimscript by doing `:require ("notify")("test")`. Instead you need to run `:lua require("notify")("test")`
