### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by lougreenwood** [rcarriga/nvim-notify#231]
I use AstroNvim, which pins it's dependency on `nvim-notify` to `^3`.

I was browsing the docs for `notify` and I saw the `wrapped-compact` renderer and though this looked quite nice. However since AstroNvim pins it's releases and `wrapped-compact` wasn't in a new release yet I wasted a bunch of time trying to figure out why it was missing and notify was saying it couldn't find the rendered.

It was only when I saw that `wrapped-compact` was merged 2 months ago and the `3.12` was released in Jun that I realised it's because I don't track master...

**Comment by rcarriga** [comment]
Hadn't noticed but fixed the pipeline and a new release has been created :smile:
