### ISSUE TITLE
Unable to get yank, write and undo to display in nvim-notify

### ISSUE THREAD

**Issue by basava70** [rcarriga/nvim-notify#238]
Hi, 
Thanks for the awesome plugin. It is amazing. I want to see yank and write to be displayed into nvim-notify.
![Screenshot from 2023-12-17 03-20-23](https://github.com/rcarriga/nvim-notify/assets/124213816/c597c6e6-a1c5-47af-af3e-c1316102bc55)
I still get all the other notifications, like " file created", "file deleted" and some other error messages. I want to understand what am I missing.

Thanks in advance.

**Comment by rcarriga** [comment]
This is a question for noice.nvim, nvim-notify does not send these notifications
