### ISSUE TITLE
[bug] `attempt to index a number value` in multiple places after recent fixes in neovim

### ISSUE THREAD

**Issue by embe221ed** [rcarriga/nvim-notify#252]
Hello, I've noticed that building NeoVim with [this commit](https://github.com/neovim/neovim/commit/f9d81c43d2296d212c9cebcbdce401cd76cf0f1f) breaks the plugin.
The floating windows are displayed incorrectly, without text, like this:
<img width="2048" alt="Screenshot 2024-02-09 at 10 38 20" src="https://github.com/rcarriga/nvim-notify/assets/26097838/a2bec82f-08b2-4a6d-8e5b-2da0e08b74ca">

I believe, the fix would consist of removing the `[false]` parts, I guess they were used as a workaround for something.

**Comment by galk-research** [comment]
Same problem happening after latest update through AstroNvim.  Sorry, can you elaborate on the fix?  I tried switching this plugin version back v3.13.1, but this broke other parts in astronvim.

**Comment by bellini666** [comment]
This should fix the issue: https://github.com/rcarriga/nvim-notify/pull/251

**Comment by utrumo** [comment]
On arch now i just rebuild neovim to previous commit from src:

paru --chroot -Rsun neovim-nightly-bin tree-sitter
paru --chroot --fm vim  -S neovim-git
add commit hash in neovim-git.PKGBUILD:
```
  "git+https://github.com/neovim/$_pkgname.git"
to
  "git+https://github.com/neovim/$_pkgname.git#commit=02cc84b4d9d8efdd27c3f60fef11e02297051fab"
```

**Comment by pfernandom** [comment]
This error is getting a bit annoying and I'm to lazy to move back to pre-nightly nvim, so I posted a PR to fix this issue.

**Comment by tan-wei** [comment]
Met the same issue when update neovim-nightly.

**Comment by loqusion** [comment]
Can confirm #253 fixes the issue for me
