### ISSUE TITLE
Unable to see entire message in a notification

### ISSUE THREAD

**Issue by Jimmytheprofessionaldumbass** [rcarriga/nvim-notify#256]
<img width="1680" alt="Screenshot 2024-02-12 at 8 42 54 PM" src="https://github.com/rcarriga/nvim-notify/assets/103012079/c2006ada-3673-4380-b20d-cf676f8e9ddb">
I usually do g< to see what is wrong but this time nvim-notify caught it, but now I can't see the message

**Comment by kmoschcau** [comment]
You can try these things:
- focus the notification (using the mouse or `Ctrl-W W`) and just navigate in it like any other buffer
- use `:Notifications` (or `:Telescope notify`) to open a list of notifications and browse those.

**Comment by rcarriga** [comment]
You can use the `wrapped-compact` renderer, see https://github.com/rcarriga/nvim-notify/pull/223
