### ISSUE TITLE
feature: keep window conditionally alive

### ISSUE THREAD

**Issue by danielnehrig** [rcarriga/nvim-notify#3]
allow for a property in config that keeps the window alive by a condition (not time bound)

**Comment by rcarriga** [comment]
Interesting idea, do you have a particular use case in mind just as an example?

**Comment by danielnehrig** [comment]
1. running tests, running builds with neomake/compiler
2. hover over lsp error keep showing notify window until leaving error line
i think i can find more use cases if needed @rcarriga

**Comment by danielnehrig** [comment]
lgtm
