### ISSUE TITLE
Using nvim-notify messes up bufferline/statusline colors

### ISSUE THREAD

**Issue by shaunsingh** [rcarriga/nvim-notify#37]
https://user-images.githubusercontent.com/71196912/144071794-6d7ac33a-7a0d-4bd0-b1d8-77822feea87e.mov

After running something that triggers nvim-notify (in this case `:PackerCompile`, I use ivim-notify for `vim.notify`), the colors for my status line and buffer line get messed up.

**Comment by rcarriga** [comment]
That's a very odd bug, are you able to verify in another UI or in a terminal? When the colours change, what's the value of the highlight groups of your bufferline/statusline once they change? You can check with `:hi <group name>` to see the colours. If the colours are correct then I'd imagine it's a UI bug

**Comment by Johan-Palacios** [comment]
> Sin título.mov 
> Después de ejecutar algo que activa nvim-notify (en este caso, uso ivim-notify para ), los colores de mi línea de estado y línea de búfer se estropean.`:PackerCompile``vim.notify`

This is not an answer, but since you added so that nvim-notify works for you with the notifications of the status bar, I am curious XD

**Comment by bryant-the-coder** [comment]
@shaunsingh how u have that smoooth mouse cursor??

**Comment by shaunsingh** [comment]
The Neovide GUI does the cursor effects
>  You can check with :hi <group name> to see the colours. If the colours are correct then I'd imagine it's a UI bug
Oddly enough the colors remain correct. What I recently did was get the colors for my BufferLine from my color scheme rather than from a Lua table, then the issue resolved itself.
