### ISSUE TITLE
Value expected as fourth argument but function only takes three

### ISSUE THREAD

**Issue by nwithers-ecr** [rcarriga/nvim-notify#38]
### Description
I mistakenly assumed this was related to #31 but after trying that solution it still failed and I noticed the error message differs slightly. 
When I first start nvim I see
```
Error running notification service: ...art/nvim-notify/lua/notify/service/buffer/highlights.lua:59: bad argument #4 to 'blend' (value expected)
```

But when I dig down into the code, highlights.lua:59 is calling blend from util/init.lua:43
However, blend only takes and is given three arguments, so why is it expecting a 4th value? 
##### service/buffer/highlights.lua
```
updated_fields[name] = util.blend(value, background, alpha / 100)
```
##### util/init.lua
```
function M.blend(fg_hex, bg_hex, alpha)
```
### highlight settings
`morhetz/gruvbox` is the gruvbox plugin
```vim
-- Color scheme and highlights
vim.o.signcolumn = 'auto'
vim.o.colorcolumn = '80'
vim.o.background = 'dark'
vim.cmd 'syntax on'
vim.cmd 'colorscheme gruvbox'
vim.cmd 'hi Normal guifg=fg guibg=bg ctermfg=fg ctermbg=bg'
-- names defined here https://camo.githubusercontent.com/410b3ab80570bcd5b470a08d84f93caa5b4962ccd994ebceeb3d1f78364c2120/687474703a2f2f692e696d6775722e636f6d2f776136363678672e706e67
```

### nvim -V1out.txt
```
could not source "/etc/xdg/xdg-i3/nvim/sysinit.vim"
could not source "/etc/xdg/nvim/sysinit.vim"
could not source "$VIM/sysinit.vim"
not found in runtime path: "ftdetect/*.lua"
not found in runtime path: "syntax/notify.vim syntax/notify/*.vim"
not found in runtime path: "syntax/notify.lua syntax/notify/*.lua"
Error running notification service: ...art/nvim-notify/lua/notify/service/buffer/highlights.lua:59: bad argument #4 to 'blend' (value expected)
not found in 'packpath': "pack/*/start/matchit"
not found in runtime path: "autoload/sneak.vim"
not found in 'packpath': "start/*"
not found in runtime path: "plugin/**/*.vim"
Reading ShaDa file "/home/nwithers/.local/share/nvim/shada/main.shada" info marks oldfiles

-- INSERT --

Writing ShaDa file "/home/nwithers/.local/share/nvim/shada/main.shada"
```

**Comment by rcarriga** [comment]
Are you setting a `background_colour` value in your setup? I believe that's the issue, it just wasn't being caught by validation. It should be caught now. If not could you tell me what you're passing to the setup if anything?

**Comment by nwithers-ecr** [comment]
I originally wasn't passing background_colour to setup. However, now I am passing 
```
vim.notify.setup {
  background_colour = "Normal"
}
```
and it still fails with the same error

**Comment by nwithers-ecr** [comment]
Ok, looks like I was able to solve this by setting [termguicolors](https://vimhelp.org/options.txt.html#%27termguicolors%27)
because [ctermfg](https://vimhelp.org/syntax.txt.html#highlight-ctermfg) uses indexes instead of hex values,

**Comment by rcarriga** [comment]
Ah yes `termguicolors` is required, I will add a check for that thank you!
