### ISSUE TITLE
Question related notification rendering

### ISSUE THREAD

**Issue by Iamafnan** [rcarriga/nvim-notify#39]
Hey I like this plugin so much I have a question related the rendering style of the notification. Is there any way to change the rendering style for only one notification

**Comment by rcarriga** [comment]
Glad you're enjoying it :grin: You can change the rendering for a single notification the same as you can with the setup by passing a `render` function in the options. See `:help notify-render()` for more info

**Comment by Iamafnan** [comment]
Thanks😄
