### ISSUE TITLE
enhancement: detect tabline to offset the notification

### ISSUE THREAD

**Issue by lazytanuki** [rcarriga/nvim-notify#4]
Hi and thanks a lot for this plugin, it's very nice to use ! 😀

I just have a small issue : when a notification appears it will appear on top of the tabline, messing up it's background.
It's not a big deal but I've seen other plugins (not about notifications) that detect when the tabline is present to avoid such things.

![image](https://user-images.githubusercontent.com/43273245/128408675-5af612b7-c87d-4201-b70c-421535f8b5cf.png)

Thanks again and have a good day !

LazyTanuki

**Comment by rcarriga** [comment]
Thanks for the great feedback :grin: Good idea, I hadn't noticed this issue. Please try with the latest commit!

**Comment by lazytanuki** [comment]
Well that was fast ! Works great, thanks again ! 😉
