### ISSUE TITLE
Allow for on_close callback during setup

### ISSUE THREAD

**Issue by resolritter** [rcarriga/nvim-notify#40]
On `require("notify").setup`, the user can provide an `on_open` callback for when windows are opened. This is a request to also allow for `on_close`.

Without the `on_close` callback, the user is forced to do manual bookkeeping on the windows, like so

```lua
windows = {}

require("notify").setup({
  on_open = function(window)
    table.insert(windows, window)
  end
})

on_window_closed = function(window)
  -- do something here if the window is one of the windows being tracked
end

vim.cmd [[ autocmd WinClosed * call v:lua.on_window_closed(expand("<afile>")) ]]
```

Not only suboptimal, it's also potentially unreliable since the `nvim_win_close` calls in the current code are wrapped in `pcall`, thus there might be case where WinClosed is not fired for some reason (e.g. the window did not exist anymore) due to an error and the event goes unnoticed.

**Comment by rcarriga** [comment]
Please try latest commit :smile:

**Comment by resolritter** [comment]
Thanks for the feature!

I was expecting `on_close` to be called in the places where nvim_win_close is called, such as

https://github.com/rcarriga/nvim-notify/blob/ee79a5e2f8bde0ebdf99880a98d1312da83a3caa/lua/notify/service/init.lua#L58

And also

https://github.com/rcarriga/nvim-notify/blob/ee79a5e2f8bde0ebdf99880a98d1312da83a3caa/lua/notify/windows/init.lua#L114

Even more so because the `on_open` counterpart is called after `nvim_win_open`

https://github.com/rcarriga/nvim-notify/blob/280a08ca5d005b1f504fbc4906db69c23f109ccc/lua/notify/stages/util.lua#L48-L51

https://github.com/rcarriga/nvim-notify/blob/ee79a5e2f8bde0ebdf99880a98d1312da83a3caa/lua/notify/windows/init.lua#L55-L60

I might be missing something but it seems like https://github.com/rcarriga/nvim-notify/commit/ef027e34b618eac42fb0111c1db670ba01793039 will not be effective for what I am thinking of

**Comment by rcarriga** [comment]
During every frame of the animation loop there is a check for if the window is still open, if not then the `WindowAnimator:remove_win` function is called.
https://github.com/rcarriga/nvim-notify/blob/master/lua/notify/windows/init.lua#L148

This function is also called at the end of the window lifecycle. Therefore it will handle both the window closing normally as well as if another action closes it.

If you find otherwise then please let me know but I see no issue for what you need

**Comment by resolritter** [comment]
I'll try it out!

Thanks for the explanation and the plugin as well.
