### ISSUE TITLE
after last update   broke something --ef027e3

### ISSUE THREAD

**Issue by hideObush** [rcarriga/nvim-notify#41]
sorry for my bad engilsh.. 
but it has problem after update ef027e3

`E5108: Error executing lua ...k/packer/start/nvim-notify/lua/notify/render/default.lua:14: E523: Not allowed here
stack traceback:
        [C]: in function 'nvim_buf_set_lines'
        ...k/packer/start/nvim-notify/lua/notify/render/default.lua:14: in function 'render'
        ...ker/start/nvim-notify/lua/notify/service/buffer/init.lua:88: in function 'render'
        ...ack/packer/start/nvim-notify/lua/notify/service/init.lua:41: in function 'push'
        ...m/site/pack/packer/start/nvim-notify/lua/notify/init.lua:96: in function 'notify'
        ...m/site/pack/packer/start/nvim-notify/lua/notify/init.lua:181: in function <...m/site/pack/packer/start/n
vim-notify/lua/notify/init.lua:175>
        /home/hjkl/.config/nvim/after/plugin/notify.lua:20: in function 'notify'
        ...e/pack/packer/start/express_line.nvim/lua/el/builtin.lua:217: in function 'responsive_file'
        /home/hjkl/.config/nvim/after/plugin/statusline.lua:103: in function 'statusline_generator'
        ...site/pack/packer/start/express_line.nvim/lua/el/init.lua:70: in function '__index'
        ...site/pack/packer/start/express_line.nvim/lua/el/init.lua:147: in function 'run'
        [string "luaeval()"]:1: in main chunk`

> 

NVIM v0.7.0-dev+688-g5abd7c2c1

**Comment by rcarriga** [comment]
So it doesn't happen before that change? Can you show me how you are sending the notification? Also please your setup

**Comment by hideObush** [comment]
sry.. i had remove notify and feature ..after saw your messages  and i install again ... it perfactly works fine no error mes  ,sry for wasting your time
