### ISSUE TITLE
Support: Way to clear all notifications?

### ISSUE THREAD

**Issue by joshpetit** [rcarriga/nvim-notify#42]
Hey! So I occasionally get a lot of notifications, so I was wondering if there was a function I could call to clear all those notifications?

**Comment by rcarriga** [comment]
There is now :grin: Try `require("notify").dismiss({pending = true})` in latest commit

**Comment by joshpetit** [comment]
Beautiful stuff!

**Comment by ilan-schemoul** [comment]
Good, I wish it was documented on the readme tho
