### ISSUE TITLE
highlights.lua:59: bad argument #4 to 'blend' (value expected)

### ISSUE THREAD

**Issue by HaleTom** [rcarriga/nvim-notify#44]
In my `.vimrc` I have:

```
lua require("notify")("My super important message")
```
Upon load, I see the message:

```
``Error running notification service: ...che/vimrc/.dein/lua/notify/service/buffer/highlights.lua:59: bad argument #4 to 'blend' (value expected)```
```

**Comment by rcarriga** [comment]
What's the output of `:hi Normal`?

**Comment by MikeOlsen** [comment]
Same error for me:
`Normal         xxx ctermfg=223 ctermbg=235 guifg=#ebdbb2 guibg=#282828`

**Comment by rcarriga** [comment]
Do you have `termguicolors` set? (`:echo &termguicolors` should print 1)

**Comment by MikeOlsen** [comment]
Apparently not, it works now that I have enabled it. Thanks!

**Comment by rcarriga** [comment]
I'm going to assume @HaleTom you were having the same issue and will close this. If setting `termguicolors` does not work, please feel free to re-open
