### ISSUE TITLE
Notify popup cannot be closed when doing :NvimTreeClose

### ISSUE THREAD

**Issue by dkeithdj** [rcarriga/nvim-notify#45]
As the title suggests, is there a way to immediately close the notify popup when doing `:NvimTreeClose` while the popup is still present?
**Here's an example**
![nvimRecord](https://user-images.githubusercontent.com/42316655/147191185-37f34887-7c4e-4271-a6b2-89e6ca751af9.gif)
I've also opened an issue regarding with this one on nvim-tree repo [here](https://github.com/kyazdani42/nvim-tree.lua/issues/859)

**Comment by rcarriga** [comment]
This is an issue in nvim-tree not handling floating windows, I've opened a PR there. Since you have an issue open there as well, I'll close this as it's not specific to nvim-notify
