### ISSUE TITLE
crash and conflict

### ISSUE THREAD

**Issue by darzok0914** [rcarriga/nvim-notify#46]
hi, I'm not sure if this is an nvim core issue or a nui-nvim issue, but it seems like when a notification is already displayed  and still being displayed and we try to open a popup window using the nui-nvim plugin the call fail and result in a crash. 

also I noticed that if Telescope is open and a notification appears it will close the telescope window. 

is it possible to prevent notification to show up when telescope is open and for all notification to disappear via a function call, so that for example before opening a pop-up buffer we can clear the notification and prevent a crash?

**Comment by rcarriga** [comment]
The telescope issue is not an issue with nvim-notify. I've opened a separate issue there to discuss it.

There is already a `dismiss` that will clear notifications but I'm curious about the crash you're describing. Is it a hard crash which causes neovim to exit (e.g. segfault)? Or just a lot of errors?

**Comment by rcarriga** [comment]
OK from investigation it looks like telescope closing is a quirk of neovim and can't be worked around by telescope. I've updated the window options to set `noautocmd` as a workaround for nvim-notify.

**Comment by darzok0914** [comment]
hi thank you so much for taking the time to investigate and I apologise for my late response, I have a been a bit on and off lately due to illness, could you provide an example on how to use this workaround ?

**Comment by rcarriga** [comment]
No worries at all! It should just work now, if not please let me know
