### ISSUE TITLE
Highlight group `Normal` has no background highlight.

### ISSUE THREAD

**Issue by ray-x** [rcarriga/nvim-notify#47]
Hi, I am using a color sheme with transparent background, which means the bg of Normal is not set.
But the plugin seems not happy with it and pop up the warning message each time. Is it possible to disable this warning?

**Comment by ray-x** [comment]
maybe, as a feature request, would be great to support transparent background. Reset floating background to '#000000' is not what I expect as well.

**Comment by rcarriga** [comment]
Just provide a value for the `background_colour` option as the warning instructs
```
Please provide an RGB hex value or highlight group with a background value for 'background_colour' option

Defaulting to #000000
```
or use a style that doesn't require opacity changes.

> maybe, as a feature request, would be great to support transparent background. Reset floating background to #000000 is not what I expect as well.

Not sure I understand what you mean here? If the user wants to use a fading window, then there needs to be a background colour for the window to blend with. There's no way of knowing this automatically so it by default will "guess" by using the `Normal` background colour, and if it doesn't exist (i.e. using a transparent background) then the user needs to provide a colour (e.g. the background colour of their termnal)

**Comment by ray-x** [comment]
The transparent color looks like this:
![image](https://user-images.githubusercontent.com/1681295/147710823-f3bac4f1-08df-4957-9c97-3d20b56989e4.png)
I do not think setting bg to any color will have same look and feel.
Is it possible only fade-in/out the text and border, not the background?   Or, keep bg to transparent when using fade in/out.

**Comment by rcarriga** [comment]
The background colour setting is not setting the background colour of the window, it is setting the colour to blend the text with. Have you tried setting it? I don't think I see the problem?

**Comment by ray-x** [comment]
I can not hard code background_colour to a specific color.
I have multiple color schemes. They are lazy-loading randomly (based on time of the day).  Is it possible to set  background_colour to a function?
Also, another question here. If I change the color scheme after notify setup(), e.g. from dark to light. Will it affect the blend?

**Comment by rcarriga** [comment]
OK dynamic background is not a problem, I've added that ability in the latest commit. You can set it to a function to dynamically return RGB values or it will now update along with the color scheme if set to a highlight group which is what I believe you are asking here
> If I change the color scheme after notify setup(), e.g. from dark to light. Will it affect the blend?

**Comment by ray-x** [comment]
Thanks, it is very helpful!

**Comment by axieax** [comment]
![image](https://user-images.githubusercontent.com/62098008/147800288-bdb7c9f2-4a89-459f-8a63-de60269af04c.png)

Hi! Not sure if I'm doing this correctly, but is it possible to winblend so that the background doesn't look as dark, i.e. same colour as background, but transparent? I've been trying to get this to work for a very long time 🥲

**Comment by rcarriga** [comment]
AFAIK winblend is not able to be used with transparent backgrounds, it's been an open issue for years https://github.com/neovim/neovim/issues/10685

**Comment by axieax** [comment]
I see! Thanks for bringing this to my attention :)
