### ISSUE TITLE
Crash in nvim-tree

### ISSUE THREAD

**Issue by Nils75owo** [rcarriga/nvim-notify#48]
Hi im having the problem that when i open a folder in nvim (which gets opened in nvim-tree) and there are messages on startup nvim crashes when there is no other buffer open when the message dissapers
![image](https://user-images.githubusercontent.com/81255505/148060870-49021b87-d50e-4963-9e72-18fcd8d889e5.png)
as soon as the message dissapers nvim crashes
![image](https://user-images.githubusercontent.com/81255505/148060990-139e245b-c0ca-4a70-9416-c14248113dda.png)
this doesnt crash bc i opened an other buffer
this also happens with the default settings

**Comment by Nils75owo** [comment]
This also happens with the VGit buffers

**Comment by rcarriga** [comment]
This is happening because of the auto close feature, this is an issue for nvim-tree. It needs to handle floating windows somehow
