### ISSUE TITLE
Store output of command and show it in notification window.

### ISSUE THREAD

**Issue by LinArcX** [rcarriga/nvim-notify#49]
For instance i want to show `:pwd` in notification window. or output of a more complicated function/command. How do that in nvim-notify?

**Comment by rcarriga** [comment]
You could use the redir command `:redir`. If you wanted to use it in lua you could do something like this
```lua
local function command_output(cmd)
  vim.cmd("redir => g:_command_output | silent " .. cmd .. " | redir END ")
  local output = vim.g._command_output
  vim.g._command_output = nil
  return output
end

vim.notify(command_output("pwd"))
```
