### ISSUE TITLE
enhancement: Take over all stdout's of neovim by default? 

### ISSUE THREAD

**Issue by glyh** [rcarriga/nvim-notify#5]
I really like this plugin, and I don't like vim's default outputline(i.e. at the bottom). 
So is there a way that we can take over all stdouts?

**Comment by rcarriga** [comment]
Glad you're enjoying the plugin! I don't think this would be possible right now as that'd require overriding the `echo`/`echom` commands (possibly others) which AFAIK is not possible right now as they are implemented in C. You could ask on the NeoVim repo if it would be possible but I'd imagine there would be a tonne of complexity behind a change like that.

**Comment by teto** [comment]
`:messages` is really bad, there has been some attempts https://github.com/neovim/neovim/pull/6374 to improve it bot nothing concrete yet. vim.notify is a way to bypass that but eventually we'll improve `:messages`. For now it's not possible to do what you ask.

**Comment by zeertzjq** [comment]
Possible solutions in Nvim: <https://github.com/neovim/neovim/pull/16396>, <https://github.com/neovim/neovim/pull/16383>.

**Comment by glyh** [comment]
https://github.com/neovim/neovim/pull/16396 is merged, we may consider add some options for it later.

**Comment by rcarriga** [comment]
I don't think it can be used just yet, it seems the dependency on `ext_cmdline` causes some issues. I'm testing with
```lua
vim.ui_attach(
  vim.api.nvim_create_namespace("redirect messages"),
  { ext_messages = true },
  function(event, ...)
    if event == "msg_show" then
      local level = vim.log.levels.INFO
      local kind, content = ...
      if string.find(kind, "err") then
        level = vim.log.levels.ERROR
      end
      vim.notify(content, level, { title = "Message" })
    end
  end
)
```

**Comment by folke** [comment]
I just **silently** (for now) released a new plugin that does this and a lot more. See https://github.com/folke/noice.nvim

Feel free to test it out and give some feedback :)

**Comment by folke** [comment]
@rcarriga during blocking events, we sometimes need to render the messages without any delays. 

When that's the case, I use a separate notify instance with `stages=static`, but that is not enough to make it work in realtime.

I'm currently patching `NoifyService.push` in https://github.com/folke/noice.nvim/blob/79f1ac9c524d14d5497065533ac9faa6ab38fe6e/lua/noice/hacks.lua#L144

Would be good to have this fixed within Notify itself, but I'm not sure what a proper fix is?

**Comment by rcarriga** [comment]
Looks very cool, I'll have a go over the weekend!

Sorry if it's obvious but why do messages need to be rendered immediately during blocking events?

**Comment by folke** [comment]
for example when rendering the cmdline. But also in situations where a plugin echos a message and then waits for input. Or uses `confirm`, `inputlist`, ... Or when you open a file that is already opened in another instance of Neovim. Custom operator pending modes.

Lots of cases basically :)

**Comment by folke** [comment]
To clarify, just do something like:

```lua
vim.notify("test")
vim.getchar()
```

You won't see the message till after you entered a key. In this case, you want the initial message to be displayed instantly and prior to the blocking input.

Noice takes care of these kinds of situations automatically.

**Comment by rcarriga** [comment]
Ah thanks for explaining that makes complete sense! I think your solution is pretty much the right way to do it, I've added a forced render on creation and also the redraw

**Comment by rcarriga** [comment]
Closing this as there is too much complexity involved for this plugin and noice.nvim handles it well
