### ISSUE TITLE
How to receive the output from a terminal command like `ls -a`?

### ISSUE THREAD

**Issue by nyngwang** [rcarriga/nvim-notify#50]
As title. The real case is that I want to redirect the standard output of a cpp file to nvim-notify. Is this possible?

**Comment by Pocco81** [comment]
You can use this function to capture the output of the command, then you'd send it just like any `str` to notify:

```lua
function os_return_execute(cmd)
    local fileHandle = assert(io.popen(cmd, "r"))
    local commandOutput = assert(fileHandle:read("*a"))
    local returnTable = {fileHandle:close()}
    return commandOutput, returnTable[3] -- rc[3] contains returnCode
end
```

**Comment by nyngwang** [comment]
@Pocco81: Could you explain more about this function? To be specific I want to know whether I have to cleanup something after I run this command.

**Comment by nyngwang** [comment]
@Pocco81 How to use the second one `returnTable[3]` in `return` to change the color of notify?

**Comment by nyngwang** [comment]
I have tried changed one line to:

```
    return {commandOutput, returnTable[3]} -- rc[3] contains returnCode
```

and use `unpack` to make it possible to chain the entire thing into a one-line command (since I don't know whether the plugin depending on this one would support passing a lua function)

```
lua require'notify'(unpack(_G.os_return_execute('g++ % -std=c++20 -o $fileBase && ./$fileBase && rm ./$fileBase')))
```

**Comment by nyngwang** [comment]
@Pocco81  I found the problem. I think your code only works in Lua 5.2, but Lua in NeoVim stays at 5.1.

**Comment by rcarriga** [comment]
The above solution will block your neovim until the command exits. I'd recommend using vim.loop (libuv) instead for async handling.
```lua
local function notify_command(command)
  local stdin = vim.loop.new_pipe()
  local stdout = vim.loop.new_pipe()
  local stderr = vim.loop.new_pipe()
  local output = ""
  local error_output = ""
  vim.loop.spawn(command[1], {
    stdio = { stdin, stdout, stderr },
    detached = true,
    args = #command > 1 and vim.list_slice(command, 2, #command) or nil,
  }, function(code, _)
    stdin:close()
    stdout:close()
    stderr:close()
    if #output > 0 then
      vim.notify(output)
    end
    if #error_output > 0 then
      vim.notify(error_output, "error")
    end
    if #output == 0 and #error_output == 0 then
      vim.notify("No output of command, exit code: "..code, "warn")
    end
  end)
  stdout:read_start(function(err, data)
    if err then
      error_output = error_output .. (err or data)
      return
    end
    if data then
      output = output .. data
    end
  end)
  stderr:read_start(function(err, data)
    if err or data then
      error_output = error_output .. (err or data)
    end
  end)
end


notify_command({ "echo", "hello" })
notify_command({ "bash", "-c", "This will fail" }) -- Error
notify_command({ "sleep", 1 }) -- Warn
```

**Comment by Pocco81** [comment]
I like @rcarriga's solution

**Comment by nyngwang** [comment]
@rcarriga Thank you...! Before I saw your comment, I has been desperately trying to create one by myself for about 3 hours(, and it doesn't even work).

**Comment by nyngwang** [comment]
I think you could add a tutorial on README.md or so to let people who are not very good at Lua can facilitate this function.

**Comment by nyngwang** [comment]
@rcarriga Since I'm using `make` I still have to make sure that the output file does exist before I can execute it...

**Comment by nyngwang** [comment]
I also need to customize the title. How?

**Comment by rcarriga** [comment]
> Since I'm using make I still have to make sure that the output file does exist before I can execute it..., Is it possible to provide a queue to make sure it's executed in order?

I don't understand what your asking here? Do you mean you need to run multiple commands? Just add an extra argument to the custom function for an `on_close` callback. 

```lua
notify_command({...}, function()
    notify_command({...})
end)
```

> I also need to customize the title. How? 

The code given is setting the title.
```lua
  local notify = function (msg, level)
    vim.notify(msg, level, { title = table.concat(command, " ") })
  end
```
You can change it however you like

**Comment by nyngwang** [comment]
> [...] Just add an extra argument to the custom function for an `on_close` callback. [...]

@rcarriga: Thanks for the info. I will try it later.

---

> I don't understand what your asking here? Do you mean you need to run multiple commands?

Yes. I need to run multiple async. commands __finished in the order I want__. So for example, if I call it like this:

```
notify_command(COMMAND_A)
notify_command(COMMAND_B)
notify_command(COMMAND_C)
```

I will expect that the order of finish is: A -> B -> C. I cannot run an executable before it is generated. I did mention this in my old comment:

> Since I'm using make I still have to make sure that the output file does exist before I can execute it...

**Comment by rcarriga** [comment]
I've added the a usage recipe to the wiki for users to see examples including the one above. I'm going to close this issue as most of the questions are general nvim/lua questions. I'd recommend checking out https://github.com/nanotee/nvim-lua-guide and asking questions on [Reddit](reddit.com/r/neovim) or [Discourse](https://neovim.discourse.group/)

**Comment by nyngwang** [comment]
Thanks!

**Comment by nyngwang** [comment]
@rcarriga Can I also edit the wiki? While you have added the `notify_command` definition, I can provide my real usage of this function that resolves the requirement I mentioned in these comment:

- https://github.com/rcarriga/nvim-notify/issues/50#issuecomment-1014755674
- https://github.com/rcarriga/nvim-notify/issues/50#issuecomment-1015514573
