### ISSUE TITLE
syntax highlighting

### ISSUE THREAD

**Issue by Josiah-tan** [rcarriga/nvim-notify#51]
![image](https://user-images.githubusercontent.com/65082231/149767233-0f68d5aa-49b3-4ebd-97ad-193d5e970089.png)

 in this image the first one uses this plugin and the second one uses the notifications from nvim-orgmode
It would be nice if I could set the file type for the buffer so that syntax highlighting is supported

**Comment by rcarriga** [comment]
OK have this working in #86. Feel free to try it out, will merge it in soon once I make sure I haven't missed anything. You can make use of it by just changing the filetype with the `on_open` option
```lua
  on_open = function(win)
    local buf = vim.api.nvim_win_get_buf(win)
    vim.api.nvim_buf_set_option(buf, "filetype", <filetype>)
  end,

```
