### ISSUE TITLE
How do I change the entire message bg?

### ISSUE THREAD

**Issue by afreidz** [rcarriga/nvim-notify#54]
How can I change the background color of the entire message?  I dont want it to use the `Normal` highlight group.  I'd prefer to use the default ones (or some other group) and style them thru my theme.  It seems no matter what I do, some part of the message still gets the `Normal` highlight group.

![image](https://user-images.githubusercontent.com/1158247/150832567-20e2ce6d-93d7-47fd-9055-6720e0f5bb71.png)

**Comment by gadzhi-m** [comment]
I don't want to create a new topic. Can you tell me how can I install this plugin? I don't see the instructions.(

**Comment by afreidz** [comment]
what plugin? are you talking about `notify`? the instructions are in the readme for this repo. did you mean to comment on this issue?

**Comment by gadzhi-m** [comment]
> какой плагин? ты о чем `notify`? инструкции находятся в файле readme для этого репо. Вы хотели прокомментировать этот вопрос?

I'm a beginner. Usually I see how they ask in the instructions to download something and write Plug 'notify'

**Comment by afreidz** [comment]
i dont think you intend to ask that question here. the instructions for the plugin can be found [here](https://github.com/rcarriga/nvim-notify/blob/master/README.md) ... this is a github issue about.a specific problem i am having.

**Comment by rcarriga** [comment]
Your config should now work as you want. The "Body" highlight will be used as the normal highlight from now on

**Comment by afreidz** [comment]
tyvm!!!
