### ISSUE TITLE
Feature request: Additional text only to be displayed in notification history

### ISSUE THREAD

**Issue by vogelsgesang** [rcarriga/nvim-notify#57]
Some notifications (e.g., `clangd`'s AST dumps; see #56) can be quite large.
I would want to truncate the text displayed in the notification itself, and only have the full text visible in the notification history. The notification would then display something like `For the full message, look in the notification history`.

I could imagine a few alternatives on how to achieve this:
* a new `history_details` string option passed to the `notify` function. `history_details` would be a string, just as `notification`, but it would only be displayed in the history.
* a new `display_notification` boolean option passed to the `notify` function. When set to false, this message is not displayed as a notification, but only in the history. I would then call `notify` twice: once with the full text and `display_notification: false`, such that I have the full text in the history, and then a second time with the truncated message and `display_notification: true`, such that a notification is displayed on screen, telling me to look in the history.
* a new `auto_truncate` option which, when set, automatically truncates the on-screen notification but still adds the full notification text to the notification history

**Comment by rcarriga** [comment]
> a new auto_truncate option which, when set, automatically truncates the on-screen notification but still adds the full notification text to the notification history

Something along these lines is definitely the route I prefer, my thought would be a simple `max_height/max_width` config option or something similar that'd limit the length of the windows when animated. I think keeping it as a config option makes sense as currently the notification options don't have anything to do with window placement or sizing. Don't think I can see a use case for a single notification determining its dimensions outside of the user config

**Comment by vogelsgesang** [comment]
I agree, having a `max_height/max_width` config option set through the `notify.setup` option would also be my preferred solution. It's certainly most user-friendly/least effort to use. I also don't see an use case for changing `max_width`/other truncation options for individual messages

**Comment by rcarriga** [comment]
Try with the latest commit, you can now supply `max_height/max_width` settings

**Comment by vogelsgesang** [comment]
Works beautifully! Thank you!

The notification is now truncated:
<img width="1792" alt="Screenshot 2022-02-01 at 12 36 22" src="https://user-images.githubusercontent.com/6820896/151961734-b59fba47-4e45-41ed-9886-a8cf5a519463.png">


In the history it is still complete:
<img width="1792" alt="Screenshot 2022-02-01 at 12 36 46" src="https://user-images.githubusercontent.com/6820896/151961786-1b1d9f24-eba1-439f-9ca8-a4eec4cd92cd.png">

**Comment by fitrh** [comment]
Is it possible to pass `max_width/height` on every call ?
I have configuration like this:

```lua
max_width = math.floor(vim.api.nvim_win_get_width(0) / 3)
```

So I can have notification with width of 1/3 of the window width, but it seems the option only passed on setup ?

**Comment by rcarriga** [comment]
I don't really want to add window placement/sizing logic to the notifications themselves as it couples them to the implementation.

I'm a bit confused as to why you'd want to use the current window's width in the first place. What happens if you have a few splits open and the notification window ends up tiny? Or do you mean the NeoVim window as a whole?

**Comment by vogelsgesang** [comment]
interesting idea, @fitrh.
I am also switching between different screens, and a fixed max-width is of 120 characters is too small on the bigger screen and too big on the smaller screen :/ 

@rcarriga I agree that this should not be an adhoc per notification, but be part of the global configuration. I could imagine something like

```
require("notify").setup({
  max_width = function() begin
    return math.floor(vim.api.nvim_get_screen_size() / 3)
  end
})
```

(no idea how to get the size of the complete neovim window/screen. So I just made up the `nvim_get_screen_size` call.)

**Comment by fitrh** [comment]
> I'm a bit confused as to why you'd want to use the current window's width in the first place. What happens if you have a few splits open and the notification window ends up tiny? Or do you mean the NeoVim window as a whole?

Sorry, yes, I mean the whole window

**Comment by rcarriga** [comment]
OK that makes more sense to me then yes as @vogelsgesang said, this is more of a requirement for dynamically setting the value rather than setting it per notification :smile:

**Comment by rcarriga** [comment]
Please try with the latest commit
```lua
    max_width = function ()
      return math.ceil(math.max(vim.opt.columns:get() / 3, 10))
    end,
    max_height = function ()
      return math.ceil(math.max(vim.opt.lines:get() / 3, 4))
    end,
```

**Comment by fitrh** [comment]
https://user-images.githubusercontent.com/55179750/152957414-1d0037dc-b97a-4a03-83b6-f603d17e89e8.mp4

Thanks @rcarriga, it works as expected

**Comment by rcarriga** [comment]
Just noticed I pushed that commit to the wrong branch :facepalm: It's now in master
