### ISSUE TITLE
Issue with calling vim.notify in FileType command

### ISSUE THREAD

**Issue by AckslD** [rcarriga/nvim-notify#58]
I was having some issues with notifications from `nvim-lint` and it seems to be an issue when `vim.notify` is called in a `FileType` event.

If I put for example the following dummy command in my config:
```lua
vim.cmd('autocmd FileType * lua vim.notify("test")')
```
neovim borks with
```
Vim(set):E218: autocommand nesting too deep
```

Is it the case that `nvim-notify` opens a buffer or in some other way triggers `FileType` which makes this a recursive call?

**Comment by rcarriga** [comment]
Yes this is exactly what is happening. I'm not sure there's anyway to work around that. It's very odd to have a `FileType` autocmd that matches all file types. Would `BufNew` or `BufAdd` work instead?

**Comment by AckslD** [comment]
Agreed! I'd say it's probably more of a user-error than an issue with `nvim-notify`. Indeed I changed my autocmd which I had for `nvim-lint` from
```lua
vim.cmd('autocmd FileType,BufWritePost,InsertLeave * lua require("lint").try_lint()')
```
to be instead
```lua
vim.cmd('autocmd BufEnter,BufWritePost,InsertLeave * lua require("lint").try_lint()')
```

Anyway, I thought I'd report it here such that if someone makes the same mistake as me they might find it :)
