### ISSUE TITLE
Enhancement: Provide coroutine APIs

### ISSUE THREAD

**Issue by curist** [rcarriga/nvim-notify#6]
This is more of a suggestion, not much of an issue.

Could we consider to leverage lua coroutine, to avoid callback hell? It might be great to introduce that in this library.

An example wrapper may work like this

```lua
local notify = require 'notify'
function noty(...)
  local self = coroutine.running()
  local args = {...}
  local message = args[1]
  local type = args[2] or 'info'
  local opts = args[3] or {}
  opts.on_close = function()
    coroutine.resume(self)
  end
  notify(message, type, opts)
  return coroutine.yield()
end

-- and a sleep helper function
function sleep(ms)
  local self = coroutine.running()
  vim.defer_fn(function()
    coroutine.resume(self)
  end, ms)
  return coroutine.yield()
end
```

Then the example in README will be like this

```lua
notify("This is an error message.\nSomething went wrong!", "error", {
  title = plugin,
})
notify("Attempting recovery.", vim.lsp.log_levels.WARN, {
  title = plugin,
})
sleep(2000)

noty({ "Fixing problem.", "Please wait..." }, "info", {
  title = plugin,
  timeout = 3000,
})

notify("Problem solved", nil, { title = plugin })
notify("Error code 0x0395AF", 1, { title = plugin })
```

**Comment by oberblastmeister** [comment]
I created an async library in https://github.com/nvim-lua/plenary.nvim that uses coroutines. It handles many edge cases and would also be good for code reuse and standardization. It also has plans of being merged into neovim core.

**Comment by rcarriga** [comment]
I'd certainly be open to having a nicer API instead of callbacks, I do miss async/await... @oberblastmeister That looks interesting ,is there any documentation in the works for the module or examples I could look at?

**Comment by rcarriga** [comment]
Finally got around to implementing this :sweat_smile: Plenary's async module is now integrated and there is a new `async` function in the module
