### ISSUE TITLE
Bug -> when you change the "minimum_width" option, the line seperate Title and body will not change its width

### ISSUE THREAD

**Issue by SongTianxian9** [rcarriga/nvim-notify#61]
as title said, here are images show you what i mean: 
![image](https://user-images.githubusercontent.com/88336105/154023337-8b70ab98-9100-4eed-928e-05562443bd2e.png)
![image](https://user-images.githubusercontent.com/88336105/154023355-9b201927-4bc3-495b-bf85-8267eb5ea64b.png)

**Comment by rcarriga** [comment]
Not sure why you closed this but it should be fixed now :smile:
