### ISSUE TITLE
Integrate lua to regular vim format

### ISSUE THREAD

**Issue by Henry-Ta** [rcarriga/nvim-notify#62]
I'm using regular nvim with vim-plug and wondering if we can integrate this plug into initi.vim. 

My script below is not showing anything.

```vim
call plug#begin('.....\nvim\plugged')
        Plug 'rcarriga/nvim-notify'
call plug#end()

lua << EOF
vim.notify = require("notify")
EOF
```

**Comment by rcarriga** [comment]
Your current script looks correct, if you add a `call nvim_notify("test", "Info", {})` afterwards, it shows nothing?

**Comment by Henry-Ta** [comment]
I got this error after adding your command

<img width="758" alt="image" src="https://user-images.githubusercontent.com/59848305/155760697-906fa145-4f5d-4e73-acbb-6b312da2b8fd.png">

**Comment by rcarriga** [comment]
Ah sorry the vimscript version is more strict on types that can be used. Change it to `call nvim_notify("test", 1, {})`

**Comment by Henry-Ta** [comment]
Cool, I got this 

<img width="478" alt="Screen Shot 2022-02-25 at 9 43 29 AM" src="https://user-images.githubusercontent.com/59848305/155762406-1c0bb6ec-bc71-4344-b430-fe4068769941.png">

but how can I make it show up with regular notification ?

**Comment by rcarriga** [comment]
What do you mean by regular notification?

**Comment by Henry-Ta** [comment]
Probably a misconception, I expect this plug will display notifications for any actions in Neovim (error, PlugUpdate, PlugInstall, open/close tabs, ...) or we have to set it up manually for everything ? Speaking of which, what **vim.notify = require("notify")** accounts for ?

**Comment by rcarriga** [comment]
So vim.notify is a way for plugins to send messages through an interface that users can customize (e.g. by using nvim-notify). This means it is opt-in so plugin writers must explicitly call it in their code rather than using `echo`. A lot of lua based plugins do this but most that are vim-compatible will not. Using nvim-notify for all messages is currently not possible, see #5
