### ISSUE TITLE
Wiki: Documentation for LSP configuration uses `hidden` instead of `hide_from_history`

### ISSUE THREAD

**Issue by vogelsgesang** [rcarriga/nvim-notify#67]
The [usage examples on the wiki](https://github.com/rcarriga/nvim-notify/wiki/Usage-Recipes#lsp-status-updates) on the wiki is outdated. Should be `hide_from_history` instead of `hidden`.

(Unfortunately, I couldn't figure out how to create a Pull Request against the wiki page...)

**Comment by rcarriga** [comment]
Thanks for pointing out! Fixed and also opened wiki to editing by others for future
