### ISSUE TITLE
Notification width does not take title length into account

### ISSUE THREAD

**Issue by vogelsgesang** [rcarriga/nvim-notify#68]
The width used to render a notification takes only the body length into account, but not the title widht.
This means that the messages by LSP or DAP (where titles can easily be longer than the body) sometimes render badly.
For example,

```
require("notify")("Complete", "info", {title = "lldb: Parsing symbol table for test_binary", timeout = 3000})
```

renders as

<img width="506" alt="Screenshot 2022-03-14 at 10 41 16" src="https://user-images.githubusercontent.com/6820896/158146144-292642b1-25a8-420b-a6a6-331740defab9.png">

**Comment by rcarriga** [comment]
Thanks for reporting, should be taking titles into account now :grin:

**Comment by vogelsgesang** [comment]
works beautifully! Thanks :)
