### ISSUE TITLE
An warning notification beyond expected when colorscheme was set to transparent background

### ISSUE THREAD

**Issue by stark-zhang** [rcarriga/nvim-notify#69]
As this screenshot, `nvim-notify` will give a warning if following conditions were satisfied:

+ the option `stages` is set to `fade_in_slide_out`,
+ enable transparent background in colorscheme.

And it will repeat this warning hundreds of times, and create many highlight groups, looks like the second screenshot. 

![image](https://user-images.githubusercontent.com/17326718/158729257-84663529-b3c3-4f9b-82b5-20e215592715.png)

![image](https://user-images.githubusercontent.com/17326718/158729961-1852dc91-6446-400c-a027-525f357834f8.png)

How to reproduce this issue:

environment:
+ CentOS 7.9
+ nvim 0.6.1 or nightly(I have not tried this on older version)

minimal configuration:
```lua
vim.api.nvim_command [[set termguicolors]]
vim.api.nvim_command [[packadd packer.nvim]]

local packer = require('packer')
local use = packer.use

return packer.startup(function()
    use { 'wbthomason/packer.nvim', opt = true }

    -- loading colorscheme with transparent backgroud
    use {
        'folke/tokyonight.nvim',
        opt = false,
        config = function()
            vim.g.tokyonight_italic_keywords = false
            vim.g.tokyonight_italic_comments = false
            vim.g.tokyonight_transparent = true
            vim.g.tokyonight_transparent_sidebar = true
            vim.g.tokyonight_style = 'storm'

            vim.api.nvim_command([[colorscheme tokyonight]])
        end
    }

    -- loading nvim-notify
    use {
        'rcarriga/nvim-notify',
        opt = false,
        config = function()
            local notify = require('notify')
            notify.setup {
                stages = 'fade_in_slide_out',
            }

            vim.notify = notify
        end,
    }
end)

```
Then:

1. save this configuration, and install `packer.nvim` if you haven't installed it,
2. run `nvim -u init.lua +PackerSync` to make configuration avaliable,
3. restart the nvim, then run `:lua vim.notify('something here')`, you could get what shows in screenshots.

And other stages, or non-transparent background would not reproduce this issue in my test.

**Comment by Ynoop** [comment]
the same problem too。

**Comment by rcarriga** [comment]
Added a fix to stop the spam but to prevent the warning you must set the `background_colour` config value to a colour.

**Comment by stark-zhang** [comment]
> Added a fix to stop the spam but to prevent the warning you must set the `background_colour` config value to a colour.

I think giving a default value or option of backgroud color is more proper, what's your opinion about it?
