### ISSUE TITLE
Question: High cpu-usage when trying to dismiss in-progress notifications.

### ISSUE THREAD

**Issue by LinArcX** [rcarriga/nvim-notify#72]
Let me explain the scenario:

I have a c++ project that uses cmake as build-system. I want to show an in-progress notification with vim-notify and whenever my build finished(whether its successful or failed), i should stop the in-progress notification and show final message. Here is my attempt:

```
local notif_data = {}
local app = "myserver"
local has_error = false
local notify_timeout = 500
local notify_done_title = nil
local notify_in_progress_title = nil
local spinner_frames = { "⣾", "⣽", "⣻", "⢿", "⡿", "⣟", "⣯", "⣷" }

local function update_spinner(notif_data, title)
   local new_spinner = (notif_data.spinner + 1) % #spinner_frames
   notif_data.spinner = new_spinner

   notif_data.notification = require("notify").notify(title, nil, {
     hide_from_history = true,
     icon = spinner_frames[new_spinner],
     replace = notif_data.notification,
   })

   vim.defer_fn(function()
     update_spinner(notif_data, nil)
   end, 100)
end

function on_event(job_id, data, event)
  local lines = {""}
  if event == "stderr" then
    local error_lines = ""
    vim.list_extend(lines, data)

    for i=1, #lines
    do
      error_lines = error_lines .. "\n" .. lines[i]
    end

    if(lines[3] ~= nil) then
      vim.b._cexpr_lines = error_lines
      vim.cmd [[ :cexpr b:_cexpr_lines ]]
      vim.cmd [[ :copen ]]
      has_error = true

      require("notify").dismiss(true)

      require("notify").notify("Something went wrong!", "ERROR",
        { title = notify_title, timeout = notify_timeout })
    end
  end
  if event == "exit" then
    if data then
      if(not has_error) then
        update_spinner(notif_data, "SUCCESS")
        require("notify").dismiss()

        local successfull_message =  string.format("%s was successful :)", notify_done_title)
        require("notify").notify(successfull_message, "INFO",
          { title = notify_title, timeout = notify_timeout })
        vim.cmd(':source $MYVIMRC')
      end
    end
    has_error = false
  end
end

function async_task(command)
  print(notification_title)

  notif_data.notification = require("notify").notify(notify_in_progress_title, "info", {
    title = "",
    icon = spinner_frames[1],
    timeout = false,
    hide_from_history = false,
  })
  notif_data.spinner = 1
  update_spinner(notif_data, nil)

  local job_id = vim.fn.jobstart(command,
    { on_stderr = on_event,
      on_stdout = on_event,
      on_exit = on_event,
      stdout_buffered = true,
      stderr_buffered = true,
    })
end
```
It's working. But it has a bad issue. It cause high cpu-usage whenever i call build function, because of this line:

` require("notify").dismiss()`

And if i try to run build command for extra times, my whole computer will freeze and i should restart it.

I don't know is there any better way to stop an in-progress notification instead of using `dismiss()`. Any idea?

**Comment by LinArcX** [comment]
I removed this line:
`require("notify").dismiss(true)`

But still have a high cpu usage rate. What's going on here?

**Comment by rcarriga** [comment]
This seems similar to #71. Are you using the latest master commit?

**Comment by LinArcX** [comment]
Yes, i'm at master branch.

**Comment by rcarriga** [comment]
OK can you provide a sample command to run for the above code so that I can reproduce? Happy to use an open source C++ project if that works

**Comment by LinArcX** [comment]
Here you are:
https://github.com/LinArcX/embedded_programming

**Comment by LinArcX** [comment]
@rcarriga any update or news?

**Comment by rcarriga** [comment]
Haven't had a chance to test, will update when I do

**Comment by rcarriga** [comment]
OK only getting a chance to properly look at this now. 

> Edit2: Even showing a simple notification like this will cause high cpu usage:
require("notify")("My super important message") 

I did not spot this edit before but this suggests you're running this on pretty under-powered hardware. This plugin works by rerendering the window 30 times a second so there will be not insignificant CPU usage. What kind of CPU are you running this on?

**Comment by LinArcX** [comment]
> What kind of CPU are you running this on?
Before i provide the information that you asked, just __for your information__ i should say that i use lot's of big applications like chromium, xfce, gnome, etc.. on my machine and none of them cause high cpu usage like your plugin!

Anyway this is my configuration:

```
 lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         36 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  8
  On-line CPU(s) list:   0-7
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz
    CPU family:          6
    Model:               42
    Thread(s) per core:  2
    Core(s) per socket:  4
    Socket(s):           1
    Stepping:            7
    CPU max MHz:         2900.0000
    CPU min MHz:         800.0000
    BogoMIPS:            3991.15
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall n
                         x rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monit
                         or ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti t
                         pr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts
Virtualization features:
  Virtualization:        VT-x
Caches (sum of all):
  L1d:                   128 KiB (4 instances)
  L1i:                   128 KiB (4 instances)
  L2:                    1 MiB (4 instances)
  L3:                    6 MiB (1 instance)
NUMA:
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-7
Vulnerabilities:
  Itlb multihit:         KVM: Mitigation: VMX disabled
  L1tf:                  Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
  Mds:                   Vulnerable: Clear CPU buffers attempted, no microcode; SMT vulnerable
  Meltdown:              Mitigation; PTI
  Spec store bypass:     Vulnerable
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Retpolines, STIBP disabled, RSB filling
  Srbds:                 Not affected
  Tsx async abort:       Not affected
```

**Comment by rcarriga** [comment]
Ah OK yes it does just look like that's the case I'm afraid. All of those applications are mature systems with most written in compiled languages and so are well optimised. A terminal is generally not used in the way this plugin uses it :sweat_smile: I can try optimise things but it'll be a gradual process (unless there's some glaring performance issue I've missed).

What terminal emulator do you use? Some will be more performant than others so you might get an improvement with another one

**Comment by LinArcX** [comment]
I use alacritty as terminal emulator. Bash as my shell and void Linux as my distribution.

**Comment by rcarriga** [comment]
I'm going to close this issue as the solution is just "optimise" which is far too broad of an issue to track. If there are specific bottlenecks/proposals found I'll be happy to track in an issue
