### ISSUE TITLE
how to make bg transparent

### ISSUE THREAD

**Issue by bryant-the-coder** [rcarriga/nvim-notify#76]
the title says it all

**Comment by etrnal70** [comment]
I think you can set these highlight group 

```viml
highlight link NotifyERRORBody Normal
highlight link NotifyWARNBody Normal
highlight link NotifyINFOBody Normal
highlight link NotifyDEBUGBody Normal
highlight link NotifyTRACEBody Normal
```

**Comment by bryant-the-coder** [comment]
![image](https://user-images.githubusercontent.com/92417638/162410063-6e8460c8-f6be-40fe-af5c-0264ecdd9f3a.png)

**Comment by rcarriga** [comment]
There is a `background_colour` setting which you have to set to a colour value if you want a transparent background. This colour is used to calculate the highlight when changing opacity. The colour should be whatever your terminal background is

**Comment by bryant-the-coder** [comment]
so how to make it transparent? :/

**Comment by rcarriga** [comment]
Your terminal must be transparent. Your `Normal` highlight must not have a background highlight set i.e. `termbg=none`

**Comment by bryant-the-coder** [comment]
hmm i set `normal=none`

**Comment by rcarriga** [comment]
What do you mean you set `normal=none`? As in you've set the `guibg` for the `Normal` highlight to `none`? If so then you have a transparent background, you need to make your terminal emulator transparent as well if you want a transparent effect over other windows/the desktop

**Comment by bryant-the-coder** [comment]
`    hl(0, "Normal", { bg = "none", sp = "none" })`

**Comment by bryant-the-coder** [comment]
this is what i use

**Comment by rcarriga** [comment]
So then your neovim background is transparent, your terminal is what is not transparent. Configure your terminal to use transparency
