### ISSUE TITLE
how to control notify level

### ISSUE THREAD

**Issue by leisurelicht** [rcarriga/nvim-notify#77]
I want to close debug and trace notify. how I can do it.

**Comment by rcarriga** [comment]
Added the capability to choose a level, default is `info`. Please try latest commit :grin:

**Comment by leisurelicht** [comment]
> Added the capability to choose a level, default is `info`. Please try latest commit 😁

it works, thanks.

**Comment by NullVoxPopuli** [comment]
is info a correct default? I'm have a _lot_ of notifications that aren't saying anything useful with this :sweat_smile: (I'm looking to bump my `level` to `warn`, I think)

**Comment by rcarriga** [comment]
The code was assuming an upper case level :facepalm:, fixed it to work for lower case too.
