### ISSUE TITLE
How to replicate lsp example?

### ISSUE THREAD

**Issue by redxtech** [rcarriga/nvim-notify#81]
Hey, I'm using your plugin and I am curious as to how to set up the demo in this gif: https://user-images.githubusercontent.com/24252670/152641078-92f3da72-f49f-4705-aec8-86512693445f.gif

I would very much like to show a notification when my language server starts up, along with the progress loader beforehand.

**Comment by rcarriga** [comment]
There's an example here https://github.com/rcarriga/nvim-notify/wiki/Usage-Recipes#progress-updates
