### ISSUE TITLE
Dump notifications

### ISSUE THREAD

**Issue by TornaxO7** [rcarriga/nvim-notify#82]
Hi! I'm getting some error messages which are outputted through the notifications.
How can I dump or copy my notifications into my clipboard?

**Comment by rcarriga** [comment]
There's a `:Notifications` command to a log of the history. There's also a telescope extension which can open the notifications in a new window.

If that doesn't work then you can use the `require("notify").history` function to create your own way to show them

**Comment by TornaxO7** [comment]
That's not (really) what I meant.

Normally you would get an error message if you found a bug, as a result the error message is printed out with `vim.notify`. Now when I reported the bug/error message I couldn't dump the output of the error message to paste it into my the issue-ticket. I needed to create a screenshot which is mostly not as good as the error message in a code block.

So what I'm thinking (or expecting) is to have a command which opens a new window with the notificactions-history (or something like that), to be able to copy+paste some notifications.

## Alternatives
Yes, using the telescope extension coud be possible (I didn't knew about it, so thank you for the information) but I think a small command wouldn't be bad as well.

Is it possible to create a provided command like `:NotificationsDump` for this plugin? Can this be done by creating a new window and writing there the stuff from `require("notify").history()`? Should I (try) help here (by doing a PR)?

**Comment by rcarriga** [comment]
The telescope notification is able to open a new window already so I don't see much point in adding another one. I don't wish to add solutions for many use cases into this repo and instead allow users to have a good interface to write their own in a simple piece of lua code. For example to dump all messages to a floating window
```lua
local history = require("notify").history()

local lines = {}
for _, notif in ipairs(history) do
  for _, line in ipairs(notif.message) do
    table.insert(lines, line)
  end
end

local buf = vim.api.nvim_create_buf(false, true)

vim.api.nvim_buf_set_lines(buf, 0, -1, false, lines)

vim.api.nvim_open_win(buf, true, {
  relative = "editor",
  width = 150,
  height = 30,
  row = 0,
  col = 0,
  border = "single",
})
```

Appreciate the offer for help, I'd be happy to receive a code snippet to add to the wiki for usage recipes :smile:

**Comment by TornaxO7** [comment]
Hm... ok, could you please tell me the name of this telescope extension? I can't find it [here](https://github.com/nvim-telescope/telescope.nvim/wiki/Extensions) if I search the keyword `not`

**Comment by rcarriga** [comment]
It's already built-in to nvim-notify https://github.com/rcarriga/nvim-notify#viewing-history

**Comment by TornaxO7** [comment]
ah, thank you!
