### ISSUE TITLE
Unusual highlighting behavior

### ISSUE THREAD

**Issue by askfiy** [rcarriga/nvim-notify#85]
I found that now when the message is about to close it will have a brief highlight exception.

![Peek 2022-04-24 18-12](https://user-images.githubusercontent.com/81478335/164971602-de957b92-ec48-4433-b8fd-d4c37598287c.gif)

Below is my minimal configuration:

```
set rtp+=~/.local/share/nvim/site/pack/packer/opt/nvim-notify

" ~/.local/share/nvim/site/pack/packer/opt/
set completeopt=menuone,noselect

lua <<EOF

vim.o.termguicolors = true

vim.notify = require("notify")
vim.notify.setup()

EOF

" runtime! after/plugin/*.lua
```

**Comment by rcarriga** [comment]
Unfortunately your config doesn't reproduce for me. Are you launching with `nvim --clean -u init.vim`? Looks like something specific to your colour scheme that might be going wrong in the colour calculation.

**Comment by askfiy** [comment]
Really, I should check out the color scheme. Thanks you.

**Comment by rcarriga** [comment]
Sorry I meant something in your colour scheme that nvim-notify isn't handling well so it's still an issue. What background colour setting have you provided to notify.setup?

**Comment by askfiy** [comment]
I have now changed the animation to `static` and everything is back to normal.
my setup is like this
When the background is transparent, it is #fff, and when the background is opaque, it is Normal.

**Comment by rcarriga** [comment]
Ah OK so there is actually no error just a misunderstanding I think. The background colour setting is the colour that the highlights will fade in from and out to give the illusion of transparency. This colour should be the same as your terminal background which looks quite dark from the screenshot. Providing `#FFFFFF` (assuming this, `#FFF` is not a valid value) will make the highlights go towards white when opacity is 0 which is what is seen in the screenshot.

To solve this, just change your background colour setting to whatever you have set in your terminal

**Comment by askfiy** [comment]
That's it, I just shorthand #FFFFFF, but the problem is that I don't have a background color in transparent mode.

So.. I can only use `static` to avoid this problem.
