### ISSUE TITLE
Customize notification borders

### ISSUE THREAD

**Issue by j-hui** [rcarriga/nvim-notify#89]
Is it possible to customize the borders of the floating windows this plugin creates? Currently it seems like it just uses "rounded", but would it be possible to expose the ability to specificy what border style to use?

**Comment by gegoune** [comment]
You can override `on_open` in `setup({)}`:

```lua
  on_open = function(win)
    if vim.api.nvim_win_is_valid(win) then
      vim.api.nvim_win_set_config(win, { border = {'your border', 'chars', '…' })
    end
  end,
```
