### ISSUE TITLE
Add bottom to top example

### ISSUE THREAD

**Issue by RaafatTurki** [rcarriga/nvim-notify#90]
I understand that I need to create my own stages table to configure where and how my notifications look.
However all examples use the `available_row()` utility function which I believe only puts notifications top to bottom.

**Comment by rcarriga** [comment]
I've made the `available_slot` function  as a more generic solution so you can supply a direction to start notifications from. Just change the direction to the one you want, so in this case change to `BOTTOM_UP`

**Comment by RaafatTurki** [comment]
Works great!
Thanks.
